obj-$(CONFIG_SDP_GPIO)		+= sdp1106_gpio.o
obj-$(CONFIG_ARCH_SDP1106)	+= sdp1106.o sdp1106_misc.o

#obj-$(CONFIG_CPU_FREQ)		+= sdp1106_cpufreq.o sdp1106_asv.o
#
#ifeq ($(CONFIG_SDP_THERMAL),y)
#obj-$(CONFIG_ARCH_SDP1106)	+= sdp1106_tmu.o
#endif
