#obj-y	+= common.o
#obj-y	+= nvt_hwmem.o
obj-y	+= ndp_hwmem.o

#NVT UNZIP
obj-$(CONFIG_NVT_UNZIP)         += nvt_unzip.o
obj-$(CONFIG_NVT_UNZIP_AUTH)         += nvt_auth.o
#obj-$(CONFIG_NVT_UNZIP_TEST)            += nvt_unzip_test.o
obj-$(CONFIG_POWER_SAVING_MODE)	+= nvt_powersave.o
