#ifndef _GPIO_NVT_CHIP_172_H
#define _GPIO_NVT_CHIP_172_H

#define KER_GPIO_GROUP_PHY_ADDR_GPA	(0xFD0F0000)
#define KER_GPIO_GROUP_PHY_ADDR_GPB	(0xFD0F0200)
#define KER_GPIO_GROUP_PHY_ADDR_GPC	(0xFD100000)
#define KER_GPIO_GROUP_PHY_ADDR_GPD	(0xFD110000)
#define KER_GPIO_GROUP_PHY_ADDR_GPE	(0xFD110200)

enum EN_KER_GPIO_GROUP {
	//STBC GPIO Group
	EN_KER_GPIO_GROUP_STBC_GPF = 0,  	// GPF 0~31	//GPF6~11 is dedicated GPIOS
	EN_KER_GPIO_GROUP_STBC_START = EN_KER_GPIO_GROUP_STBC_GPF,
	EN_KER_GPIO_GROUP_STBC_GPG,		// GPG 0~26	//GPG4~7 is dedicated GPIOS
	EN_KER_GPIO_GROUP_STBC_END = EN_KER_GPIO_GROUP_STBC_GPG,

	//MIPS GPIO group 
	EN_KER_GPIO_GROUP_MIPS_GPA,         // MIPS - GPA
	EN_KER_GPIO_GROUP_MIPS_START = EN_KER_GPIO_GROUP_MIPS_GPA,	
	EN_KER_GPIO_GROUP_MIPS_GPB,         // MIPS - GPB
	EN_KER_GPIO_GROUP_MIPS_GPC,         // MIPS - GPC
	EN_KER_GPIO_GROUP_MIPS_GPD,         // MIPS - GPD
	EN_KER_GPIO_GROUP_MIPS_GPE,         // MIPS - GPE
	EN_KER_GPIO_GROUP_MIPS_END	= EN_KER_GPIO_GROUP_MIPS_GPE,

	EN_KER_GPIO_GROUP_NULL 		= EN_KER_GPIO_GROUP_MIPS_END,
	EN_KER_GPIO_GROUP_TOTAL,

	EN_KER_GPIO_GROUP_STBC_GROUP_NUM = (EN_KER_GPIO_GROUP_STBC_END- EN_KER_GPIO_GROUP_STBC_START +1),
	EN_KER_GPIO_GROUP_MIPS_GROUP_NUM = (EN_KER_GPIO_GROUP_MIPS_END- EN_KER_GPIO_GROUP_MIPS_START +1)

};

typedef enum _EN_DRV_MIPS_GPIO_GROUP {
	EN_KER_MIPS_GPIO_GROUP_MIPS_GPA,         // MIPS - GPA
	EN_KER_MIPS_GPIO_GROUP_MIPS_START = EN_KER_MIPS_GPIO_GROUP_MIPS_GPA,	
	EN_KER_MIPS_GPIO_GROUP_MIPS_GPB,         // MIPS - GPB
	EN_KER_MIPS_GPIO_GROUP_MIPS_GPC,         // MIPS - GPC
	EN_KER_MIPS_GPIO_GROUP_MIPS_GPD,         // MIPS - GPD
	EN_KER_MIPS_GPIO_GROUP_MIPS_GPE,         // MIPS - GPE
	EN_KER_MIPS_GPIO_GROUP_MIPS_END = EN_KER_MIPS_GPIO_GROUP_MIPS_GPE,

	EN_KER_MIPS_GPIO_GROUP_MIPS_MAX 
} EN_DRV_MIPS_GPIO_GROUP;
enum EN_GPIO_PIN_INDEX_KER {
	EN_GPIO_PIN_S_GPF_START_INDEX_KER = 0X0600,//GPF major number
	EN_GPIO_PIN_S_GPF_0_INDEX_KER = EN_GPIO_PIN_S_GPF_START_INDEX_KER,
	EN_GPIO_PIN_S_GPF_1_INDEX_KER,
	EN_GPIO_PIN_S_GPF_2_INDEX_KER,
	EN_GPIO_PIN_S_GPF_3_INDEX_KER,
	EN_GPIO_PIN_S_GPF_4_INDEX_KER,
	EN_GPIO_PIN_S_GPF_5_INDEX_KER,
	EN_GPIO_PIN_S_GPF_6_INDEX_KER,
	EN_GPIO_PIN_S_GPF_7_INDEX_KER,
	EN_GPIO_PIN_S_GPF_8_INDEX_KER,
	EN_GPIO_PIN_S_GPF_9_INDEX_KER,
	EN_GPIO_PIN_S_GPF_10_INDEX_KER,
	EN_GPIO_PIN_S_GPF_11_INDEX_KER,
	EN_GPIO_PIN_S_GPF_12_INDEX_KER,
	EN_GPIO_PIN_S_GPF_13_INDEX_KER,
	EN_GPIO_PIN_S_GPF_14_INDEX_KER,
	EN_GPIO_PIN_S_GPF_15_INDEX_KER,
	EN_GPIO_PIN_S_GPF_16_INDEX_KER,
	EN_GPIO_PIN_S_GPF_17_INDEX_KER,
	EN_GPIO_PIN_S_GPF_18_INDEX_KER,
	EN_GPIO_PIN_S_GPF_19_INDEX_KER,
	EN_GPIO_PIN_S_GPF_20_INDEX_KER,
	EN_GPIO_PIN_S_GPF_21_INDEX_KER,
	EN_GPIO_PIN_S_GPF_22_INDEX_KER,
	EN_GPIO_PIN_S_GPF_23_INDEX_KER,
	EN_GPIO_PIN_S_GPF_24_INDEX_KER,
	EN_GPIO_PIN_S_GPF_25_INDEX_KER,
	EN_GPIO_PIN_S_GPF_26_INDEX_KER,
	EN_GPIO_PIN_S_GPF_27_INDEX_KER,
	EN_GPIO_PIN_S_GPF_28_INDEX_KER,
	EN_GPIO_PIN_S_GPF_29_INDEX_KER,
	EN_GPIO_PIN_S_GPF_30_INDEX_KER,
	EN_GPIO_PIN_S_GPF_31_INDEX_KER,
	EN_GPIO_PIN_S_GPF_END_INDEX_KER=EN_GPIO_PIN_S_GPF_31_INDEX_KER,
	
	EN_GPIO_PIN_S_GPG_START_INDEX_KER = 0X0700,//GPG major number
	EN_GPIO_PIN_S_GPG_0_INDEX_KER = EN_GPIO_PIN_S_GPG_START_INDEX_KER,
	EN_GPIO_PIN_S_GPG_1_INDEX_KER,
	EN_GPIO_PIN_S_GPG_2_INDEX_KER,
	EN_GPIO_PIN_S_GPG_3_INDEX_KER,
	EN_GPIO_PIN_S_GPG_4_INDEX_KER,
	EN_GPIO_PIN_S_GPG_5_INDEX_KER,
	EN_GPIO_PIN_S_GPG_6_INDEX_KER,
	EN_GPIO_PIN_S_GPG_7_INDEX_KER,
	EN_GPIO_PIN_S_GPG_8_INDEX_KER,
	EN_GPIO_PIN_S_GPG_9_INDEX_KER,
	EN_GPIO_PIN_S_GPG_10_INDEX_KER,
	EN_GPIO_PIN_S_GPG_11_INDEX_KER,
	EN_GPIO_PIN_S_GPG_12_INDEX_KER,
	EN_GPIO_PIN_S_GPG_13_INDEX_KER,
	EN_GPIO_PIN_S_GPG_14_INDEX_KER,
	EN_GPIO_PIN_S_GPG_15_INDEX_KER,
	EN_GPIO_PIN_S_GPG_16_INDEX_KER,
	EN_GPIO_PIN_S_GPG_17_INDEX_KER,
	EN_GPIO_PIN_S_GPG_18_INDEX_KER,
	EN_GPIO_PIN_S_GPG_19_INDEX_KER,
	EN_GPIO_PIN_S_GPG_20_INDEX_KER,
	EN_GPIO_PIN_S_GPG_21_INDEX_KER,
	EN_GPIO_PIN_S_GPG_22_INDEX_KER,
	EN_GPIO_PIN_S_GPG_23_INDEX_KER,
	EN_GPIO_PIN_S_GPG_24_INDEX_KER,
	EN_GPIO_PIN_S_GPG_25_INDEX_KER,
	EN_GPIO_PIN_S_GPG_26_INDEX_KER,
	EN_GPIO_PIN_S_GPG_END_INDEX_KER=EN_GPIO_PIN_S_GPG_26_INDEX_KER,

	EN_GPIO_PIN_S_GPI_START_INDEX_KER = 0X0900,//GPI major number
	EN_GPIO_PIN_S_GPI_0_INDEX_KER = EN_GPIO_PIN_S_GPI_START_INDEX_KER,
	EN_GPIO_PIN_S_GPI_1_INDEX_KER,
	EN_GPIO_PIN_S_GPI_2_INDEX_KER,
	EN_GPIO_PIN_S_GPI_3_INDEX_KER,
	EN_GPIO_PIN_S_GPI_4_INDEX_KER,
	EN_GPIO_PIN_S_GPI_5_INDEX_KER,
	EN_GPIO_PIN_S_GPI_6_INDEX_KER,
	EN_GPIO_PIN_S_GPI_7_INDEX_KER,
	EN_GPIO_PIN_S_GPI_8_INDEX_KER,
	EN_GPIO_PIN_S_GPI_9_INDEX_KER,
	EN_GPIO_PIN_S_GPI_10_INDEX_KER,
	EN_GPIO_PIN_S_GPI_11_INDEX_KER,
	EN_GPIO_PIN_S_GPI_12_INDEX_KER,
	EN_GPIO_PIN_S_GPI_13_INDEX_KER,
	EN_GPIO_PIN_S_GPI_14_INDEX_KER,
	EN_GPIO_PIN_S_GPI_15_INDEX_KER,
	EN_GPIO_PIN_S_GPI_16_INDEX_KER,
	EN_GPIO_PIN_S_GPI_17_INDEX_KER,
	EN_GPIO_PIN_S_GPI_18_INDEX_KER,
	EN_GPIO_PIN_S_GPI_19_INDEX_KER,
	EN_GPIO_PIN_S_GPI_20_INDEX_KER,
	EN_GPIO_PIN_S_GPI_END_INDEX_KER=EN_GPIO_PIN_S_GPI_20_INDEX_KER,

	
	EN_GPIO_PIN_M_GPA_START_INDEX_KER = 0X0100,//GPA major number
	EN_GPIO_PIN_M_GPA_0_INDEX_KER = EN_GPIO_PIN_M_GPA_START_INDEX_KER,
	EN_GPIO_PIN_M_GPA_1_INDEX_KER,
	EN_GPIO_PIN_M_GPA_2_INDEX_KER,
	EN_GPIO_PIN_M_GPA_3_INDEX_KER,
	EN_GPIO_PIN_M_GPA_4_INDEX_KER,
	EN_GPIO_PIN_M_GPA_5_INDEX_KER,
	EN_GPIO_PIN_M_GPA_6_INDEX_KER,
	EN_GPIO_PIN_M_GPA_7_INDEX_KER,
	EN_GPIO_PIN_M_GPA_8_INDEX_KER,
	EN_GPIO_PIN_M_GPA_9_INDEX_KER,
	EN_GPIO_PIN_M_GPA_10_INDEX_KER,
	EN_GPIO_PIN_M_GPA_11_INDEX_KER,
	EN_GPIO_PIN_M_GPA_12_INDEX_KER,
	EN_GPIO_PIN_M_GPA_13_INDEX_KER,
	EN_GPIO_PIN_M_GPA_14_INDEX_KER,
	EN_GPIO_PIN_M_GPA_15_INDEX_KER,
	EN_GPIO_PIN_M_GPA_16_INDEX_KER,
	EN_GPIO_PIN_M_GPA_17_INDEX_KER,
	EN_GPIO_PIN_M_GPA_18_INDEX_KER,
	EN_GPIO_PIN_M_GPA_19_INDEX_KER,
	EN_GPIO_PIN_M_GPA_20_INDEX_KER,
	EN_GPIO_PIN_M_GPA_21_INDEX_KER,
	EN_GPIO_PIN_M_GPA_22_INDEX_KER,
	EN_GPIO_PIN_M_GPA_23_INDEX_KER,
	EN_GPIO_PIN_M_GPA_24_INDEX_KER,
	EN_GPIO_PIN_M_GPA_25_INDEX_KER,
	EN_GPIO_PIN_M_GPA_26_INDEX_KER,
	EN_GPIO_PIN_M_GPA_27_INDEX_KER,
	EN_GPIO_PIN_M_GPA_28_INDEX_KER,
	EN_GPIO_PIN_M_GPA_29_INDEX_KER,
	EN_GPIO_PIN_M_GPA_30_INDEX_KER,
	EN_GPIO_PIN_M_GPA_31_INDEX_KER,
	EN_GPIO_PIN_M_GPA_END_INDEX_KER=EN_GPIO_PIN_M_GPA_31_INDEX_KER,
	


	EN_GPIO_PIN_M_GPB_START_INDEX_KER = 0X0200,//GPB major number
	EN_GPIO_PIN_M_GPB_0_INDEX_KER = EN_GPIO_PIN_M_GPB_START_INDEX_KER,
	EN_GPIO_PIN_M_GPB_1_INDEX_KER,
	EN_GPIO_PIN_M_GPB_2_INDEX_KER,
	EN_GPIO_PIN_M_GPB_3_INDEX_KER,
	EN_GPIO_PIN_M_GPB_4_INDEX_KER,
	EN_GPIO_PIN_M_GPB_5_INDEX_KER,
	EN_GPIO_PIN_M_GPB_6_INDEX_KER,
	EN_GPIO_PIN_M_GPB_7_INDEX_KER,
	EN_GPIO_PIN_M_GPB_8_INDEX_KER,
	EN_GPIO_PIN_M_GPB_9_INDEX_KER,
	EN_GPIO_PIN_M_GPB_10_INDEX_KER,
	EN_GPIO_PIN_M_GPB_11_INDEX_KER,
	EN_GPIO_PIN_M_GPB_12_INDEX_KER,
	EN_GPIO_PIN_M_GPB_13_INDEX_KER,
	EN_GPIO_PIN_M_GPB_14_INDEX_KER,
	EN_GPIO_PIN_M_GPB_15_INDEX_KER,
	EN_GPIO_PIN_M_GPB_16_INDEX_KER,
	EN_GPIO_PIN_M_GPB_17_INDEX_KER,
	EN_GPIO_PIN_M_GPB_18_INDEX_KER,
	EN_GPIO_PIN_M_GPB_19_INDEX_KER,
	EN_GPIO_PIN_M_GPB_20_INDEX_KER,
	EN_GPIO_PIN_M_GPB_21_INDEX_KER,
	EN_GPIO_PIN_M_GPB_22_INDEX_KER,


	EN_GPIO_PIN_M_GPB_23_INDEX_KER,
	EN_GPIO_PIN_M_GPB_24_INDEX_KER,
	EN_GPIO_PIN_M_GPB_END_INDEX_KER=EN_GPIO_PIN_M_GPB_24_INDEX_KER,
	
	EN_GPIO_PIN_M_GPC_START_INDEX_KER = 0X0300,//GPC major number
	EN_GPIO_PIN_M_GPC_0_INDEX_KER = EN_GPIO_PIN_M_GPC_START_INDEX_KER,
	EN_GPIO_PIN_M_GPC_1_INDEX_KER,
	EN_GPIO_PIN_M_GPC_2_INDEX_KER,
	EN_GPIO_PIN_M_GPC_3_INDEX_KER,
	EN_GPIO_PIN_M_GPC_4_INDEX_KER,
	EN_GPIO_PIN_M_GPC_5_INDEX_KER,
	EN_GPIO_PIN_M_GPC_6_INDEX_KER,
	EN_GPIO_PIN_M_GPC_7_INDEX_KER,
	EN_GPIO_PIN_M_GPC_8_INDEX_KER,
	EN_GPIO_PIN_M_GPC_9_INDEX_KER,
	EN_GPIO_PIN_M_GPC_10_INDEX_KER,
	EN_GPIO_PIN_M_GPC_11_INDEX_KER,
	EN_GPIO_PIN_M_GPC_12_INDEX_KER,
	EN_GPIO_PIN_M_GPC_13_INDEX_KER,
	EN_GPIO_PIN_M_GPC_14_INDEX_KER,
	EN_GPIO_PIN_M_GPC_15_INDEX_KER,
	EN_GPIO_PIN_M_GPC_16_INDEX_KER,
	EN_GPIO_PIN_M_GPC_17_INDEX_KER,
	EN_GPIO_PIN_M_GPC_18_INDEX_KER,
	EN_GPIO_PIN_M_GPC_19_INDEX_KER,
	EN_GPIO_PIN_M_GPC_20_INDEX_KER,
	EN_GPIO_PIN_M_GPC_END_INDEX_KER=EN_GPIO_PIN_M_GPC_20_INDEX_KER,
	
	EN_GPIO_PIN_M_GPD_START_INDEX_KER = 0X0400,//GPD major number
	EN_GPIO_PIN_M_GPD_0_INDEX_KER = EN_GPIO_PIN_M_GPD_START_INDEX_KER,
	EN_GPIO_PIN_M_GPD_1_INDEX_KER,
	EN_GPIO_PIN_M_GPD_2_INDEX_KER,
	EN_GPIO_PIN_M_GPD_3_INDEX_KER,
	EN_GPIO_PIN_M_GPD_4_INDEX_KER,
	EN_GPIO_PIN_M_GPD_5_INDEX_KER,
	EN_GPIO_PIN_M_GPD_6_INDEX_KER,
	EN_GPIO_PIN_M_GPD_7_INDEX_KER,
	EN_GPIO_PIN_M_GPD_8_INDEX_KER,
	EN_GPIO_PIN_M_GPD_9_INDEX_KER,
	EN_GPIO_PIN_M_GPD_10_INDEX_KER,
	EN_GPIO_PIN_M_GPD_11_INDEX_KER,
	EN_GPIO_PIN_M_GPD_12_INDEX_KER,
	EN_GPIO_PIN_M_GPD_13_INDEX_KER,
	EN_GPIO_PIN_M_GPD_14_INDEX_KER,
	EN_GPIO_PIN_M_GPD_15_INDEX_KER,
	EN_GPIO_PIN_M_GPD_16_INDEX_KER,
	EN_GPIO_PIN_M_GPD_17_INDEX_KER,
	EN_GPIO_PIN_M_GPD_18_INDEX_KER,
	EN_GPIO_PIN_M_GPD_19_INDEX_KER,

	EN_GPIO_PIN_M_GPD_20_INDEX_KER,
	EN_GPIO_PIN_M_GPD_21_INDEX_KER,
	EN_GPIO_PIN_M_GPD_22_INDEX_KER,
	EN_GPIO_PIN_M_GPD_23_INDEX_KER,
	EN_GPIO_PIN_M_GPD_24_INDEX_KER,
	EN_GPIO_PIN_M_GPD_25_INDEX_KER,
	EN_GPIO_PIN_M_GPD_26_INDEX_KER,
	EN_GPIO_PIN_M_GPD_27_INDEX_KER,
	EN_GPIO_PIN_M_GPD_28_INDEX_KER,
	EN_GPIO_PIN_M_GPD_29_INDEX_KER,
	EN_GPIO_PIN_M_GPD_30_INDEX_KER,
	EN_GPIO_PIN_M_GPD_31_INDEX_KER,
	EN_GPIO_PIN_M_GPD_END_INDEX_KER=EN_GPIO_PIN_M_GPD_31_INDEX_KER,

	EN_GPIO_PIN_M_GPE_START_INDEX_KER = 0X0500,//GPE major number
	EN_GPIO_PIN_M_GPE_0_INDEX_KER = EN_GPIO_PIN_M_GPE_START_INDEX_KER,
	EN_GPIO_PIN_M_GPE_1_INDEX_KER,
	EN_GPIO_PIN_M_GPE_2_INDEX_KER,
	EN_GPIO_PIN_M_GPE_3_INDEX_KER,
	EN_GPIO_PIN_M_GPE_4_INDEX_KER,
	EN_GPIO_PIN_M_GPE_5_INDEX_KER,
	EN_GPIO_PIN_M_GPE_6_INDEX_KER,
	EN_GPIO_PIN_M_GPE_7_INDEX_KER,
	EN_GPIO_PIN_M_GPE_8_INDEX_KER,
	EN_GPIO_PIN_M_GPE_9_INDEX_KER,
	EN_GPIO_PIN_M_GPE_10_INDEX_KER,
	EN_GPIO_PIN_M_GPE_11_INDEX_KER,
	EN_GPIO_PIN_M_GPE_12_INDEX_KER,
	EN_GPIO_PIN_M_GPE_13_INDEX_KER,
	EN_GPIO_PIN_M_GPE_14_INDEX_KER,
	EN_GPIO_PIN_M_GPE_15_INDEX_KER,
	EN_GPIO_PIN_M_GPE_16_INDEX_KER,
	EN_GPIO_PIN_M_GPE_17_INDEX_KER,
	EN_GPIO_PIN_M_GPE_18_INDEX_KER,
	
	EN_GPIO_PIN_M_GPE_19_INDEX_KER,
	EN_GPIO_PIN_M_GPE_20_INDEX_KER,
	EN_GPIO_PIN_M_GPE_21_INDEX_KER,
	EN_GPIO_PIN_M_GPE_22_INDEX_KER,
	EN_GPIO_PIN_M_GPE_23_INDEX_KER,
	EN_GPIO_PIN_M_GPE_24_INDEX_KER,
	EN_GPIO_PIN_M_GPE_END_INDEX_KER=EN_GPIO_PIN_M_GPE_24_INDEX_KER
};

enum EN_KER_GPIO_PIN {
	EN_KER_GPIO_GPA_0,
	EN_KER_GPIO_GPA_START= EN_KER_GPIO_GPA_0,
	EN_KER_GPIO_GPA_1,
	EN_KER_GPIO_GPA_2,
	EN_KER_GPIO_GPA_3,
	EN_KER_GPIO_GPA_4,
	EN_KER_GPIO_GPA_5,
	EN_KER_GPIO_GPA_6,
	EN_KER_GPIO_GPA_7,
	EN_KER_GPIO_GPA_8,
	EN_KER_GPIO_GPA_9,
	EN_KER_GPIO_GPA_10,
	EN_KER_GPIO_GPA_11,
	EN_KER_GPIO_GPA_12,
	EN_KER_GPIO_GPA_13,
	EN_KER_GPIO_GPA_14,
	EN_KER_GPIO_GPA_15,
	EN_KER_GPIO_GPA_16,
	EN_KER_GPIO_GPA_17,
	EN_KER_GPIO_GPA_18,
	EN_KER_GPIO_GPA_19,
	EN_KER_GPIO_GPA_20,
	EN_KER_GPIO_GPA_21,
	
	EN_KER_GPIO_GPA_22,
	EN_KER_GPIO_GPA_23,
	EN_KER_GPIO_GPA_24,
	EN_KER_GPIO_GPA_25,
	EN_KER_GPIO_GPA_26,
	EN_KER_GPIO_GPA_27,
	EN_KER_GPIO_GPA_28,
	EN_KER_GPIO_GPA_29,
	EN_KER_GPIO_GPA_30,
	EN_KER_GPIO_GPA_31,
	EN_KER_GPIO_GPA_END= EN_KER_GPIO_GPA_31,


	EN_KER_GPIO_GPB_0,
	EN_KER_GPIO_GPB_START = EN_KER_GPIO_GPB_0,
	EN_KER_GPIO_GPB_1,
	EN_KER_GPIO_GPB_2,
	EN_KER_GPIO_GPB_3,
	EN_KER_GPIO_GPB_4,
	EN_KER_GPIO_GPB_5,
	EN_KER_GPIO_GPB_6,
	EN_KER_GPIO_GPB_7,
	EN_KER_GPIO_GPB_8,
	EN_KER_GPIO_GPB_9,
	EN_KER_GPIO_GPB_10,
	EN_KER_GPIO_GPB_11,
	EN_KER_GPIO_GPB_12,
	EN_KER_GPIO_GPB_13,
	EN_KER_GPIO_GPB_14,
	EN_KER_GPIO_GPB_15,
	EN_KER_GPIO_GPB_16,
	EN_KER_GPIO_GPB_17,
	EN_KER_GPIO_GPB_18,
	EN_KER_GPIO_GPB_19,
	EN_KER_GPIO_GPB_20,
	EN_KER_GPIO_GPB_21,
	EN_KER_GPIO_GPB_22,

	EN_KER_GPIO_GPB_23,
	EN_KER_GPIO_GPB_24,

	EN_KER_GPIO_GPB_END = EN_KER_GPIO_GPB_24,

	EN_KER_GPIO_GPC_0,
	EN_KER_GPIO_GPC_START = EN_KER_GPIO_GPC_0,
	EN_KER_GPIO_GPC_1,
	EN_KER_GPIO_GPC_2,
	EN_KER_GPIO_GPC_3,
	EN_KER_GPIO_GPC_4,
	EN_KER_GPIO_GPC_5,
	EN_KER_GPIO_GPC_6,
	EN_KER_GPIO_GPC_7,
	EN_KER_GPIO_GPC_8,
	EN_KER_GPIO_GPC_9,
	EN_KER_GPIO_GPC_10,
	EN_KER_GPIO_GPC_11,
	EN_KER_GPIO_GPC_12,
	EN_KER_GPIO_GPC_13,
	EN_KER_GPIO_GPC_14,
	EN_KER_GPIO_GPC_15,
	EN_KER_GPIO_GPC_16,
	EN_KER_GPIO_GPC_17,
	EN_KER_GPIO_GPC_18,
	EN_KER_GPIO_GPC_19,
	EN_KER_GPIO_GPC_20,
	EN_KER_GPIO_GPC_END = EN_KER_GPIO_GPC_20,

	EN_KER_GPIO_GPD_0,
	EN_KER_GPIO_GPD_START = EN_KER_GPIO_GPD_0,
	EN_KER_GPIO_GPD_1,
	EN_KER_GPIO_GPD_2,
	EN_KER_GPIO_GPD_3,
	EN_KER_GPIO_GPD_4,
	EN_KER_GPIO_GPD_5,
	EN_KER_GPIO_GPD_6,
	EN_KER_GPIO_GPD_7,
	EN_KER_GPIO_GPD_8,
	EN_KER_GPIO_GPD_9,
	EN_KER_GPIO_GPD_10,
	EN_KER_GPIO_GPD_11,
	EN_KER_GPIO_GPD_12,
	EN_KER_GPIO_GPD_13,
	EN_KER_GPIO_GPD_14,
	EN_KER_GPIO_GPD_15,
	EN_KER_GPIO_GPD_16,
	EN_KER_GPIO_GPD_17,
	EN_KER_GPIO_GPD_18,
	EN_KER_GPIO_GPD_19,

	EN_KER_GPIO_GPD_20,
	EN_KER_GPIO_GPD_21,
	EN_KER_GPIO_GPD_22,
	EN_KER_GPIO_GPD_23,
	EN_KER_GPIO_GPD_24,
	EN_KER_GPIO_GPD_25,
	EN_KER_GPIO_GPD_26,
	EN_KER_GPIO_GPD_27,
	EN_KER_GPIO_GPD_28,
	EN_KER_GPIO_GPD_29,
	EN_KER_GPIO_GPD_30,
	EN_KER_GPIO_GPD_31,
	EN_KER_GPIO_GPD_END = EN_KER_GPIO_GPD_31,



	EN_KER_GPIO_GPE_0,
	EN_KER_GPIO_GPE_START = EN_KER_GPIO_GPE_0,
	EN_KER_GPIO_GPE_1,
	EN_KER_GPIO_GPE_2,
	EN_KER_GPIO_GPE_3,
	EN_KER_GPIO_GPE_4,
	EN_KER_GPIO_GPE_5,
	EN_KER_GPIO_GPE_6,
	EN_KER_GPIO_GPE_7,
	EN_KER_GPIO_GPE_8,
	EN_KER_GPIO_GPE_9,
	EN_KER_GPIO_GPE_10,
	EN_KER_GPIO_GPE_11,
	EN_KER_GPIO_GPE_12,
	EN_KER_GPIO_GPE_13,
	EN_KER_GPIO_GPE_14,
	EN_KER_GPIO_GPE_15,
	EN_KER_GPIO_GPE_16,
	EN_KER_GPIO_GPE_17,
	EN_KER_GPIO_GPE_18,

	EN_KER_GPIO_GPE_19,
	EN_KER_GPIO_GPE_20,
	EN_KER_GPIO_GPE_21,
	EN_KER_GPIO_GPE_22,
	EN_KER_GPIO_GPE_23,
	EN_KER_GPIO_GPE_24,
	EN_KER_GPIO_GPE_END = EN_KER_GPIO_GPE_24,
	

	EN_KER_GPIO_PIN_TOTAL, 
	EN_KER_GPIO_PIN_NULL = EN_KER_GPIO_PIN_TOTAL,

	EN_KER_GPIO_GPA_NUM = (EN_KER_GPIO_GPA_END-EN_KER_GPIO_GPA_START + 1), 	
	EN_KER_GPIO_GPB_NUM = (EN_KER_GPIO_GPB_END-EN_KER_GPIO_GPB_START + 1),	
	EN_KER_GPIO_GPC_NUM = (EN_KER_GPIO_GPC_END-EN_KER_GPIO_GPC_START + 1),	
	EN_KER_GPIO_GPD_NUM = (EN_KER_GPIO_GPD_END-EN_KER_GPIO_GPD_START + 1),	
	EN_KER_GPIO_GPE_NUM = (EN_KER_GPIO_GPE_END-EN_KER_GPIO_GPE_START + 1),
};

typedef struct _ST_KER_GPIO_DRIVING_PARAM
{
	EN_DRV_MIPS_GPIO_GROUP	enGrp;
	unsigned int u32PhyAddr;
} ST_KER_GPIO_DRIVING_PARAM;

typedef struct NTGPIO_PadConfig_s {
	unsigned int PullUpReg;
	unsigned int PullDnReg;
	unsigned char Shift1;
	unsigned int DS0; /* Driving Strength-0 */
	unsigned int DS1; /* Driving Strength-1 */
} NTGPIO_PadConfig_t;

typedef struct _ST_GPIO_DESCRIPTION_KER {
	unsigned int u8Function; /* define in ss tDagpiotable.h */
	unsigned int enPin;
} ST_GPIO_DESCRIPTION_KER;

#endif //_GPIO_NVT_CHIP_685
