/* ********************************************************************* */

/*  File Name: ntgpio.h */

/*  Description: gpio driver */

/* ********************************************************************* */

#ifndef _NTGPIO_H
#define _NTGPIO_H


#include <linux/platform_device.h>	/* struct device* */
#include <linux/gpio.h>
#include <linux/ioctl.h>

/* for ErrMsg output standard	added 050915 */
#define GPIO_DBG_NONE_BG	"\x1b[0m"
#define GPIO_DBG_RED_BG	"\x1b[0;32;41m"
#define GPIO_MSG_PREFIX_ERR GPIO_DBG_RED_BG"[ERR_DRV_GPIO]"GPIO_DBG_NONE_BG

#ifdef DEBUG
#define GPIO_DBG_LOG(fmt, ...)		\
	pr_err("[%s():%d]: " fmt,		\
		__func__, __LINE__, ##__VA_ARGS__)
#else
#define GPIO_DBG_LOG(fmt, ...)
#endif

#define GPIO_INF_LOG(fmt, ...)		\
	pr_err("[ERR_BSP_GPIO][%s():%d] " fmt,		\
		__func__, __LINE__, ##__VA_ARGS__)


#define BIT_0           (1L<<0)
#define BIT_1           (1L<<1)
#define BIT_2           (1L<<2)
#define BIT_3           (1L<<3)
#define BIT_4           (1L<<4)
#define BIT_5           (1L<<5)
#define BIT_6           (1L<<6)
#define BIT_7           (1L<<7)
#define BIT_8           (1L<<8)
#define BIT_9           (1L<<9)
#define BIT_10          (1L<<10)
#define BIT_11          (1L<<11)
#define BIT_12          (1L<<12)
#define BIT_13          (1L<<13)
#define BIT_14          (1L<<14)
#define BIT_15          (1L<<15)
#define BIT_16          (1L<<16)
#define BIT_17          (1L<<17)
#define BIT_18          (1L<<18)
#define BIT_19          (1L<<19)
#define BIT_20          (1L<<20)
#define BIT_21          (1L<<21)
#define BIT_22          (1L<<22)
#define BIT_23          (1L<<23)
#define BIT_24          (1L<<24)
#define BIT_25          (1L<<25)
#define BIT_26          (1L<<26)
#define BIT_27          (1L<<27)
#define BIT_28          (1L<<28)
#define BIT_29          (1L<<29)
#define BIT_30          (1L<<30)
#define BIT_31          (1L<<31)

#define _AGPIO_CF_BUS_BIT					0x00000000
#define _AGPIO_SDMMC_BUS_BIT				0x00000001
#define _AGPIO_SMC_BUS_BIT					0x00000002
#define _AGPIO_MSPRO_BUS_BIT				0x00000003
#define _AGPIO_SPI_BUS_BIT					0x00000004
#define _AGPIO_DEBUG_GROUP_BUS_BIT		0x00000005
#define _AGPIO_CI_BUS_BIT					0x00000006
#define _AGPIO_HW_SPI_BOOTER_BUS_BIT        0x00000007


#define KER_GPIO_GROUP_PHY_ADDR_GPA	(0xFD0F0000)
#define KER_GPIO_GROUP_PHY_ADDR_GPB	(0xFD0F0200)
#define KER_GPIO_GROUP_PHY_ADDR_GPC	(0xFD100000)
#define KER_GPIO_GROUP_PHY_ADDR_GPD	(0xFD110000)
#define KER_GPIO_GROUP_PHY_ADDR_GPE	(0xFD110200)

#define KER_GPIO_HDMI_IDENT_PHY_ADDR	(0xFc040c10)
#define KER_GPIO_MHL_IDENT_PHY_ADDR	(0xFc040424)
#define GPIO_FUNCTION_MUX_MAX			(4)

struct ST_GPIO_GROUP_INFO {
	unsigned char u8group_size;
	unsigned char u8group_start;
	unsigned char u8group_end;
};
struct ST_GPIO_DESCRIPTION_KER {
	unsigned int u8Function; /* define in ss tDagpiotable.h */
	unsigned int enPin;
};
enum EN_GPIO_MUX_SELECT_DEFIN {
	EN_GPIO_MUX_SELECT_MASK,
	EN_GPIO_MUX_SELECT_FUN1,
	EN_GPIO_MUX_SELECT_FUN2,
	EN_GPIO_MUX_SELECT_FUN3,
	EN_GPIO_MUX_SELECT_FUN4,
	EN_GPIO_MUX_SELECT_FUN5,
	EN_GPIO_MUX_SELECT_FUN6,
	EN_GPIO_MUX_SELECT_FUN7,
	EN_GPIO_MUX_SELECT_MAX
};


#define MAX_GPIO_LINES		135


struct nt726xx_gpio_reg_offs {
	unsigned short revision;
	unsigned short direction;
	unsigned short datain;
	unsigned short dataout;
	unsigned short set_dataout;
	unsigned short clr_dataout;
	unsigned short irqstatus;
	unsigned short irqstatus2;
	unsigned short irqstatus_raw0;
	unsigned short irqstatus_raw1;
	unsigned short irqenable;
	unsigned short irqenable2;
	unsigned short set_irqenable;
	unsigned short clr_irqenable;
	unsigned short debounce;
	unsigned short debounce_en;
	unsigned short ctrl;
	unsigned short wkup_en;
	unsigned short leveldetect0;
	unsigned short leveldetect1;
	unsigned short risingdetect;
	unsigned short fallingdetect;
	unsigned short irqctrl;
	unsigned short edgectrl1;
	unsigned short edgectrl2;
	unsigned short pinctrl;

	bool irqenable_inv;
};

struct nt726xx_gpio_platform_data {
	int bank_type;
	int bank_width;
	bool loses_context;	/* whether the bank would ever lose context */
	unsigned int non_wakeup_gpios;
	struct nt726xx_gpio_reg_offs *regs;

	/* Return context loss count due to PM states changing */
	int (*get_context_loss_count)(struct device *dev);
};

#define GPIO_INT_EN_REG    0xFD0D0800
#define GPIO_INT_LV_REG    0xFD0D0804
#define GPIO_INT_ST_REG    0xFD0F0808

struct GPIO_REG_s {
	/* reg0x00 */
	unsigned long ulGPIOClear;

	/* reg0x04 */
	unsigned long ulGPIOSet;

	/* reg0x08 */
	unsigned long ulGPIODir;

	/* reg0x0C */
	unsigned long ulGPIODrvPin1;

	/* reg0x10 */
	unsigned long ulGPIODrvPin2;

	/* reg0x14 */
	unsigned long reserver2;

	/* reg0x18 */
	unsigned long ulGPIOPD;

	/* reg0x1C */
	unsigned long ulGPIOPU;

	/* reg0x20 */
	unsigned long ulGPIOMUX[4];
};

#ifndef TRUE
#define TRUE        (1)                  /*!< Define TRUE 1 */
#endif

#ifndef ENABLE
#define ENABLE      (1)                  /*!< Define ENABLE 1 */
#endif

#ifndef FALSE
#define FALSE       (0)                  /*!< Define FALSE 0 */
#endif

#ifndef DISABLE
#define DISABLE     (0)                  /*!< Define DISABLE 0 */
#endif



#define KER_GPIO_IOCTLID					'g'


/*  General purpose commands of ioctl system call */
#define KER_GPIO_IOINITIALISE\
			_IOW(KER_GPIO_IOCTLID, 1, ST_KER_GPIO_INIT_PARAM)
#define KER_GPIO_IOTERMINATE\
			_IO(KER_GPIO_IOCTLID, 2)
#define KER_GPIO_IOOPEN_GPIO\
			_IOW(KER_GPIO_IOCTLID, 10, ST_KER_GPIO_OP_PARAM)
#define KER_GPIO_IOCLOSE_GPIO\
			_IOW(KER_GPIO_IOCTLID, 11, EN_KER_GPIO_PIN)
#define KER_GPIO_IOSET_LEVEL\
			_IOW(KER_GPIO_IOCTLID, 12, ST_KER_GPIO_OP_PARAM)
#define KER_GPIO_IOGET_LEVEL\
			_IOWR(KER_GPIO_IOCTLID, 13, ST_KER_GPIO_OP_PARAM)
#define KER_GPIO_IOSET_DIR\
			_IOW(KER_GPIO_IOCTLID, 14, ST_KER_GPIO_OP_PARAM)
#define KER_GPIO_IOGET_DIR\
			_IOWR(KER_GPIO_IOCTLID, 15, ST_KER_GPIO_OP_PARAM)
#define KER_GPIO_IOSET_ALTMODE\
			_IOW(KER_GPIO_IOCTLID, 16, ST_KER_GPIO_OP_PARAM)
#define KER_GPIO_IOGET_ALTMODE\
			_IOWR(KER_GPIO_IOCTLID, 17, ST_KER_GPIO_OP_PARAM)


/*  Jay Hsu @ 20110611 : Set RMII Reference Clock Outuput */
#define KER_GPIO_IOSET_RMIIREFCLK\
			_IOW(KER_GPIO_IOCTLID, 19, ST_KER_GPIO_RMIICLK_PARAM)

#define KER_GPIO_IOCONFIG_PAD\
			_IOW(KER_GPIO_IOCTLID, 20, ST_KER_GPIO_PAD_PARAM)
#define KER_GPIO_IOCONFIG_INT\
			_IOW(KER_GPIO_IOCTLID, 21, ST_KER_GPIO_INT_PARAM)
#define KER_GPIO_IOFUN_INITIALISE\
			_IOW(KER_GPIO_IOCTLID, 22, ST_KER_GPIO_OP_PARAM)

#define KER_GPIO_IO_MAPWRAPPER\
			_IOW(KER_GPIO_IOCTLID, 30, ST_KER_GPIO_MAP_PARAM)
#define KER_GPIO_IOGET_PINNAME\
		_IOWR(KER_GPIO_IOCTLID, 31, ST_KER_GPIO_FUN_PIN_NAME_PARAM)

enum EN_KER_GPIO_GROUP {
	/* STBC GPIO Group */
	EN_KER_GPIO_GROUP_STBC_GPF = 0,
	EN_KER_GPIO_GROUP_STBC_START = EN_KER_GPIO_GROUP_STBC_GPF,
	EN_KER_GPIO_GROUP_STBC_GPG,
	EN_KER_GPIO_GROUP_STBC_END = EN_KER_GPIO_GROUP_STBC_GPG,

	/* MIPS GPIO group */
	EN_KER_GPIO_GROUP_MIPS_GPA,         /*  MIPS - GPA */
	EN_KER_GPIO_GROUP_MIPS_START = EN_KER_GPIO_GROUP_MIPS_GPA,
	EN_KER_GPIO_GROUP_MIPS_GPB,         /*  MIPS - GPB */
	EN_KER_GPIO_GROUP_MIPS_GPC,         /*  MIPS - GPC */
	EN_KER_GPIO_GROUP_MIPS_GPD,         /*  MIPS - GPD */
	EN_KER_GPIO_GROUP_MIPS_GPE,         /*  MIPS - GPE */
	EN_KER_GPIO_GROUP_MIPS_END	= EN_KER_GPIO_GROUP_MIPS_GPE,

	EN_KER_GPIO_GROUP_NULL		= EN_KER_GPIO_GROUP_MIPS_END,
	EN_KER_GPIO_GROUP_TOTAL,

	EN_KER_GPIO_GROUP_STBC_GROUP_NUM =
		(EN_KER_GPIO_GROUP_STBC_END - EN_KER_GPIO_GROUP_STBC_START + 1),
	EN_KER_GPIO_GROUP_MIPS_GROUP_NUM =
		(EN_KER_GPIO_GROUP_MIPS_END - EN_KER_GPIO_GROUP_MIPS_START + 1)

};
enum EN_DRV_MIPS_GPIO_GROUP {
	EN_KER_MIPS_GPIO_GROUP_MIPS_GPA,         /*  MIPS - GPA */
	EN_KER_MIPS_GPIO_GROUP_MIPS_START = EN_KER_MIPS_GPIO_GROUP_MIPS_GPA,
	EN_KER_MIPS_GPIO_GROUP_MIPS_GPB,         /*  MIPS - GPB */
	EN_KER_MIPS_GPIO_GROUP_MIPS_GPC,         /*  MIPS - GPC */
	EN_KER_MIPS_GPIO_GROUP_MIPS_GPD,         /*  MIPS - GPD */
	EN_KER_MIPS_GPIO_GROUP_MIPS_GPE,         /*  MIPS - GPE */
	EN_KER_MIPS_GPIO_GROUP_MIPS_END = EN_KER_MIPS_GPIO_GROUP_MIPS_GPE,
	EN_KER_MIPS_GPIO_GROUP_MIPS_MAX
};
enum {
	EN_GPIO_PIN_S_GPF_START_INDEX_KER = 0X0600,/* GPF major number */
	EN_GPIO_PIN_S_GPF_0_INDEX_KER = EN_GPIO_PIN_S_GPF_START_INDEX_KER,
	EN_GPIO_PIN_S_GPF_1_INDEX_KER,
	EN_GPIO_PIN_S_GPF_2_INDEX_KER,
	EN_GPIO_PIN_S_GPF_3_INDEX_KER,
	EN_GPIO_PIN_S_GPF_4_INDEX_KER,
	EN_GPIO_PIN_S_GPF_5_INDEX_KER,
	EN_GPIO_PIN_S_GPF_6_INDEX_KER,
	EN_GPIO_PIN_S_GPF_7_INDEX_KER,
	EN_GPIO_PIN_S_GPF_8_INDEX_KER,
	EN_GPIO_PIN_S_GPF_9_INDEX_KER,
	EN_GPIO_PIN_S_GPF_10_INDEX_KER,
	EN_GPIO_PIN_S_GPF_11_INDEX_KER,
	EN_GPIO_PIN_S_GPF_12_INDEX_KER,
	EN_GPIO_PIN_S_GPF_13_INDEX_KER,
	EN_GPIO_PIN_S_GPF_14_INDEX_KER,
	EN_GPIO_PIN_S_GPF_15_INDEX_KER,
	EN_GPIO_PIN_S_GPF_16_INDEX_KER,
	EN_GPIO_PIN_S_GPF_17_INDEX_KER,
	EN_GPIO_PIN_S_GPF_18_INDEX_KER,
	EN_GPIO_PIN_S_GPF_19_INDEX_KER,
	EN_GPIO_PIN_S_GPF_20_INDEX_KER,
	EN_GPIO_PIN_S_GPF_21_INDEX_KER,
	EN_GPIO_PIN_S_GPF_22_INDEX_KER,
	EN_GPIO_PIN_S_GPF_23_INDEX_KER,
	EN_GPIO_PIN_S_GPF_24_INDEX_KER,
	EN_GPIO_PIN_S_GPF_25_INDEX_KER,
	EN_GPIO_PIN_S_GPF_26_INDEX_KER,
	EN_GPIO_PIN_S_GPF_27_INDEX_KER,
	EN_GPIO_PIN_S_GPF_28_INDEX_KER,
	EN_GPIO_PIN_S_GPF_29_INDEX_KER,
	EN_GPIO_PIN_S_GPF_30_INDEX_KER,
	EN_GPIO_PIN_S_GPF_31_INDEX_KER,
	EN_GPIO_PIN_S_GPF_END_INDEX_KER = EN_GPIO_PIN_S_GPF_31_INDEX_KER,

	EN_GPIO_PIN_S_GPG_START_INDEX_KER = 0X0700,/* GPG major number */
	EN_GPIO_PIN_S_GPG_0_INDEX_KER = EN_GPIO_PIN_S_GPG_START_INDEX_KER,
	EN_GPIO_PIN_S_GPG_1_INDEX_KER,
	EN_GPIO_PIN_S_GPG_2_INDEX_KER,
	EN_GPIO_PIN_S_GPG_3_INDEX_KER,
	EN_GPIO_PIN_S_GPG_4_INDEX_KER,
	EN_GPIO_PIN_S_GPG_5_INDEX_KER,
	EN_GPIO_PIN_S_GPG_6_INDEX_KER,
	EN_GPIO_PIN_S_GPG_7_INDEX_KER,
	EN_GPIO_PIN_S_GPG_8_INDEX_KER,
	EN_GPIO_PIN_S_GPG_9_INDEX_KER,
	EN_GPIO_PIN_S_GPG_10_INDEX_KER,
	EN_GPIO_PIN_S_GPG_11_INDEX_KER,
	EN_GPIO_PIN_S_GPG_12_INDEX_KER,
	EN_GPIO_PIN_S_GPG_13_INDEX_KER,
	EN_GPIO_PIN_S_GPG_14_INDEX_KER,
	EN_GPIO_PIN_S_GPG_15_INDEX_KER,
	EN_GPIO_PIN_S_GPG_16_INDEX_KER,
	EN_GPIO_PIN_S_GPG_17_INDEX_KER,
	EN_GPIO_PIN_S_GPG_18_INDEX_KER,
	EN_GPIO_PIN_S_GPG_19_INDEX_KER,
	EN_GPIO_PIN_S_GPG_20_INDEX_KER,
	EN_GPIO_PIN_S_GPG_21_INDEX_KER,
	EN_GPIO_PIN_S_GPG_22_INDEX_KER,
	EN_GPIO_PIN_S_GPG_23_INDEX_KER,
	EN_GPIO_PIN_S_GPG_24_INDEX_KER,
	EN_GPIO_PIN_S_GPG_25_INDEX_KER,
	EN_GPIO_PIN_S_GPG_26_INDEX_KER,
	EN_GPIO_PIN_S_GPG_END_INDEX_KER = EN_GPIO_PIN_S_GPG_26_INDEX_KER,

	EN_GPIO_PIN_S_GPI_START_INDEX_KER = 0X0900,/* GPI major number */
	EN_GPIO_PIN_S_GPI_0_INDEX_KER = EN_GPIO_PIN_S_GPI_START_INDEX_KER,
	EN_GPIO_PIN_S_GPI_1_INDEX_KER,
	EN_GPIO_PIN_S_GPI_2_INDEX_KER,
	EN_GPIO_PIN_S_GPI_3_INDEX_KER,
	EN_GPIO_PIN_S_GPI_4_INDEX_KER,
	EN_GPIO_PIN_S_GPI_5_INDEX_KER,
	EN_GPIO_PIN_S_GPI_6_INDEX_KER,
	EN_GPIO_PIN_S_GPI_7_INDEX_KER,
	EN_GPIO_PIN_S_GPI_8_INDEX_KER,
	EN_GPIO_PIN_S_GPI_9_INDEX_KER,
	EN_GPIO_PIN_S_GPI_10_INDEX_KER,
	EN_GPIO_PIN_S_GPI_11_INDEX_KER,
	EN_GPIO_PIN_S_GPI_12_INDEX_KER,
	EN_GPIO_PIN_S_GPI_13_INDEX_KER,
	EN_GPIO_PIN_S_GPI_14_INDEX_KER,
	EN_GPIO_PIN_S_GPI_15_INDEX_KER,
	EN_GPIO_PIN_S_GPI_16_INDEX_KER,
	EN_GPIO_PIN_S_GPI_17_INDEX_KER,
	EN_GPIO_PIN_S_GPI_18_INDEX_KER,
	EN_GPIO_PIN_S_GPI_19_INDEX_KER,
	EN_GPIO_PIN_S_GPI_20_INDEX_KER,
	EN_GPIO_PIN_S_GPI_END_INDEX_KER = EN_GPIO_PIN_S_GPI_20_INDEX_KER,


	EN_GPIO_PIN_M_GPA_START_INDEX_KER = 0X0100,/* GPA major number */
	EN_GPIO_PIN_M_GPA_0_INDEX_KER = EN_GPIO_PIN_M_GPA_START_INDEX_KER,
	EN_GPIO_PIN_M_GPA_1_INDEX_KER,
	EN_GPIO_PIN_M_GPA_2_INDEX_KER,
	EN_GPIO_PIN_M_GPA_3_INDEX_KER,
	EN_GPIO_PIN_M_GPA_4_INDEX_KER,
	EN_GPIO_PIN_M_GPA_5_INDEX_KER,
	EN_GPIO_PIN_M_GPA_6_INDEX_KER,
	EN_GPIO_PIN_M_GPA_7_INDEX_KER,
	EN_GPIO_PIN_M_GPA_8_INDEX_KER,
	EN_GPIO_PIN_M_GPA_9_INDEX_KER,
	EN_GPIO_PIN_M_GPA_10_INDEX_KER,
	EN_GPIO_PIN_M_GPA_11_INDEX_KER,
	EN_GPIO_PIN_M_GPA_12_INDEX_KER,
	EN_GPIO_PIN_M_GPA_13_INDEX_KER,
	EN_GPIO_PIN_M_GPA_14_INDEX_KER,
	EN_GPIO_PIN_M_GPA_15_INDEX_KER,
	EN_GPIO_PIN_M_GPA_16_INDEX_KER,
	EN_GPIO_PIN_M_GPA_17_INDEX_KER,
	EN_GPIO_PIN_M_GPA_18_INDEX_KER,
	EN_GPIO_PIN_M_GPA_19_INDEX_KER,
	EN_GPIO_PIN_M_GPA_20_INDEX_KER,
	EN_GPIO_PIN_M_GPA_21_INDEX_KER,
	EN_GPIO_PIN_M_GPA_22_INDEX_KER,
	EN_GPIO_PIN_M_GPA_23_INDEX_KER,
	EN_GPIO_PIN_M_GPA_24_INDEX_KER,
	EN_GPIO_PIN_M_GPA_25_INDEX_KER,
	EN_GPIO_PIN_M_GPA_26_INDEX_KER,
	EN_GPIO_PIN_M_GPA_27_INDEX_KER,
	EN_GPIO_PIN_M_GPA_28_INDEX_KER,
	EN_GPIO_PIN_M_GPA_29_INDEX_KER,
	EN_GPIO_PIN_M_GPA_30_INDEX_KER,
	EN_GPIO_PIN_M_GPA_31_INDEX_KER,
	EN_GPIO_PIN_M_GPA_END_INDEX_KER = EN_GPIO_PIN_M_GPA_31_INDEX_KER,


	EN_GPIO_PIN_M_GPB_START_INDEX_KER = 0X0200,/* GPB major number */
	EN_GPIO_PIN_M_GPB_0_INDEX_KER = EN_GPIO_PIN_M_GPB_START_INDEX_KER,
	EN_GPIO_PIN_M_GPB_1_INDEX_KER,
	EN_GPIO_PIN_M_GPB_2_INDEX_KER,
	EN_GPIO_PIN_M_GPB_3_INDEX_KER,
	EN_GPIO_PIN_M_GPB_4_INDEX_KER,
	EN_GPIO_PIN_M_GPB_5_INDEX_KER,
	EN_GPIO_PIN_M_GPB_6_INDEX_KER,
	EN_GPIO_PIN_M_GPB_7_INDEX_KER,
	EN_GPIO_PIN_M_GPB_8_INDEX_KER,
	EN_GPIO_PIN_M_GPB_9_INDEX_KER,
	EN_GPIO_PIN_M_GPB_10_INDEX_KER,
	EN_GPIO_PIN_M_GPB_11_INDEX_KER,
	EN_GPIO_PIN_M_GPB_12_INDEX_KER,
	EN_GPIO_PIN_M_GPB_13_INDEX_KER,
	EN_GPIO_PIN_M_GPB_14_INDEX_KER,
	EN_GPIO_PIN_M_GPB_15_INDEX_KER,
	EN_GPIO_PIN_M_GPB_16_INDEX_KER,
	EN_GPIO_PIN_M_GPB_17_INDEX_KER,
	EN_GPIO_PIN_M_GPB_18_INDEX_KER,
	EN_GPIO_PIN_M_GPB_19_INDEX_KER,
	EN_GPIO_PIN_M_GPB_20_INDEX_KER,
	EN_GPIO_PIN_M_GPB_21_INDEX_KER,
	EN_GPIO_PIN_M_GPB_22_INDEX_KER,


	EN_GPIO_PIN_M_GPB_23_INDEX_KER,
	EN_GPIO_PIN_M_GPB_24_INDEX_KER,
	EN_GPIO_PIN_M_GPB_END_INDEX_KER = EN_GPIO_PIN_M_GPB_24_INDEX_KER,

	EN_GPIO_PIN_M_GPC_START_INDEX_KER = 0X0300,/* GPC major number */
	EN_GPIO_PIN_M_GPC_0_INDEX_KER = EN_GPIO_PIN_M_GPC_START_INDEX_KER,
	EN_GPIO_PIN_M_GPC_1_INDEX_KER,
	EN_GPIO_PIN_M_GPC_2_INDEX_KER,
	EN_GPIO_PIN_M_GPC_3_INDEX_KER,
	EN_GPIO_PIN_M_GPC_4_INDEX_KER,
	EN_GPIO_PIN_M_GPC_5_INDEX_KER,
	EN_GPIO_PIN_M_GPC_6_INDEX_KER,
	EN_GPIO_PIN_M_GPC_7_INDEX_KER,
	EN_GPIO_PIN_M_GPC_8_INDEX_KER,
	EN_GPIO_PIN_M_GPC_9_INDEX_KER,
	EN_GPIO_PIN_M_GPC_10_INDEX_KER,
	EN_GPIO_PIN_M_GPC_11_INDEX_KER,
	EN_GPIO_PIN_M_GPC_12_INDEX_KER,
	EN_GPIO_PIN_M_GPC_13_INDEX_KER,
	EN_GPIO_PIN_M_GPC_14_INDEX_KER,
	EN_GPIO_PIN_M_GPC_15_INDEX_KER,
	EN_GPIO_PIN_M_GPC_16_INDEX_KER,
	EN_GPIO_PIN_M_GPC_17_INDEX_KER,
	EN_GPIO_PIN_M_GPC_18_INDEX_KER,
	EN_GPIO_PIN_M_GPC_19_INDEX_KER,
	EN_GPIO_PIN_M_GPC_20_INDEX_KER,
	EN_GPIO_PIN_M_GPC_END_INDEX_KER = EN_GPIO_PIN_M_GPC_20_INDEX_KER,

	EN_GPIO_PIN_M_GPD_START_INDEX_KER = 0X0400,/* GPD major number */
	EN_GPIO_PIN_M_GPD_0_INDEX_KER = EN_GPIO_PIN_M_GPD_START_INDEX_KER,
	EN_GPIO_PIN_M_GPD_1_INDEX_KER,
	EN_GPIO_PIN_M_GPD_2_INDEX_KER,
	EN_GPIO_PIN_M_GPD_3_INDEX_KER,
	EN_GPIO_PIN_M_GPD_4_INDEX_KER,
	EN_GPIO_PIN_M_GPD_5_INDEX_KER,
	EN_GPIO_PIN_M_GPD_6_INDEX_KER,
	EN_GPIO_PIN_M_GPD_7_INDEX_KER,
	EN_GPIO_PIN_M_GPD_8_INDEX_KER,
	EN_GPIO_PIN_M_GPD_9_INDEX_KER,
	EN_GPIO_PIN_M_GPD_10_INDEX_KER,
	EN_GPIO_PIN_M_GPD_11_INDEX_KER,
	EN_GPIO_PIN_M_GPD_12_INDEX_KER,
	EN_GPIO_PIN_M_GPD_13_INDEX_KER,
	EN_GPIO_PIN_M_GPD_14_INDEX_KER,
	EN_GPIO_PIN_M_GPD_15_INDEX_KER,
	EN_GPIO_PIN_M_GPD_16_INDEX_KER,
	EN_GPIO_PIN_M_GPD_17_INDEX_KER,
	EN_GPIO_PIN_M_GPD_18_INDEX_KER,
	EN_GPIO_PIN_M_GPD_19_INDEX_KER,

	EN_GPIO_PIN_M_GPD_20_INDEX_KER,
	EN_GPIO_PIN_M_GPD_21_INDEX_KER,
	EN_GPIO_PIN_M_GPD_22_INDEX_KER,
	EN_GPIO_PIN_M_GPD_23_INDEX_KER,
	EN_GPIO_PIN_M_GPD_24_INDEX_KER,
	EN_GPIO_PIN_M_GPD_25_INDEX_KER,

	EN_GPIO_PIN_M_GPD_26_INDEX_KER,
	EN_GPIO_PIN_M_GPD_27_INDEX_KER,
	EN_GPIO_PIN_M_GPD_28_INDEX_KER,
	EN_GPIO_PIN_M_GPD_29_INDEX_KER,
	EN_GPIO_PIN_M_GPD_30_INDEX_KER,
	EN_GPIO_PIN_M_GPD_31_INDEX_KER,
	EN_GPIO_PIN_M_GPD_END_INDEX_KER = EN_GPIO_PIN_M_GPD_31_INDEX_KER,

	EN_GPIO_PIN_M_GPE_START_INDEX_KER = 0X0500,/* GPE major number */
	EN_GPIO_PIN_M_GPE_0_INDEX_KER = EN_GPIO_PIN_M_GPE_START_INDEX_KER,
	EN_GPIO_PIN_M_GPE_1_INDEX_KER,
	EN_GPIO_PIN_M_GPE_2_INDEX_KER,
	EN_GPIO_PIN_M_GPE_3_INDEX_KER,
	EN_GPIO_PIN_M_GPE_4_INDEX_KER,
	EN_GPIO_PIN_M_GPE_5_INDEX_KER,
	EN_GPIO_PIN_M_GPE_6_INDEX_KER,
	EN_GPIO_PIN_M_GPE_7_INDEX_KER,
	EN_GPIO_PIN_M_GPE_8_INDEX_KER,
	EN_GPIO_PIN_M_GPE_9_INDEX_KER,
	EN_GPIO_PIN_M_GPE_10_INDEX_KER,
	EN_GPIO_PIN_M_GPE_11_INDEX_KER,
	EN_GPIO_PIN_M_GPE_12_INDEX_KER,
	EN_GPIO_PIN_M_GPE_13_INDEX_KER,
	EN_GPIO_PIN_M_GPE_14_INDEX_KER,
	EN_GPIO_PIN_M_GPE_15_INDEX_KER,
	EN_GPIO_PIN_M_GPE_16_INDEX_KER,
	EN_GPIO_PIN_M_GPE_17_INDEX_KER,
	EN_GPIO_PIN_M_GPE_18_INDEX_KER,

	EN_GPIO_PIN_M_GPE_19_INDEX_KER,
	EN_GPIO_PIN_M_GPE_20_INDEX_KER,
	EN_GPIO_PIN_M_GPE_21_INDEX_KER,
	EN_GPIO_PIN_M_GPE_22_INDEX_KER,
	EN_GPIO_PIN_M_GPE_23_INDEX_KER,
	EN_GPIO_PIN_M_GPE_24_INDEX_KER,
	EN_GPIO_PIN_M_GPE_END_INDEX_KER = EN_GPIO_PIN_M_GPE_24_INDEX_KER

} EN_GPIO_PIN_INDEX_KER;

enum EN_KER_GPIO_PIN {
	EN_KER_GPIO_GPA_0,
	EN_KER_GPIO_GPA_START = EN_KER_GPIO_GPA_0,
	EN_KER_GPIO_GPA_1,
	EN_KER_GPIO_GPA_2,
	EN_KER_GPIO_GPA_3,
	EN_KER_GPIO_GPA_4,
	EN_KER_GPIO_GPA_5,
	EN_KER_GPIO_GPA_6,
	EN_KER_GPIO_GPA_7,
	EN_KER_GPIO_GPA_8,
	EN_KER_GPIO_GPA_9,
	EN_KER_GPIO_GPA_10,
	EN_KER_GPIO_GPA_11,
	EN_KER_GPIO_GPA_12,
	EN_KER_GPIO_GPA_13,
	EN_KER_GPIO_GPA_14,
	EN_KER_GPIO_GPA_15,
	EN_KER_GPIO_GPA_16,
	EN_KER_GPIO_GPA_17,
	EN_KER_GPIO_GPA_18,
	EN_KER_GPIO_GPA_19,
	EN_KER_GPIO_GPA_20,
	EN_KER_GPIO_GPA_21,

	EN_KER_GPIO_GPA_22,
	EN_KER_GPIO_GPA_23,
	EN_KER_GPIO_GPA_24,
	EN_KER_GPIO_GPA_25,
	EN_KER_GPIO_GPA_26,
	EN_KER_GPIO_GPA_27,
	EN_KER_GPIO_GPA_28,
	EN_KER_GPIO_GPA_29,
	EN_KER_GPIO_GPA_30,
	EN_KER_GPIO_GPA_31,
	EN_KER_GPIO_GPA_END = EN_KER_GPIO_GPA_31,


	EN_KER_GPIO_GPB_0,
	EN_KER_GPIO_GPB_START = EN_KER_GPIO_GPB_0,
	EN_KER_GPIO_GPB_1,
	EN_KER_GPIO_GPB_2,
	EN_KER_GPIO_GPB_3,
	EN_KER_GPIO_GPB_4,
	EN_KER_GPIO_GPB_5,
	EN_KER_GPIO_GPB_6,
	EN_KER_GPIO_GPB_7,
	EN_KER_GPIO_GPB_8,
	EN_KER_GPIO_GPB_9,
	EN_KER_GPIO_GPB_10,
	EN_KER_GPIO_GPB_11,
	EN_KER_GPIO_GPB_12,
	EN_KER_GPIO_GPB_13,
	EN_KER_GPIO_GPB_14,
	EN_KER_GPIO_GPB_15,
	EN_KER_GPIO_GPB_16,
	EN_KER_GPIO_GPB_17,
	EN_KER_GPIO_GPB_18,
	EN_KER_GPIO_GPB_19,
	EN_KER_GPIO_GPB_20,
	EN_KER_GPIO_GPB_21,
	EN_KER_GPIO_GPB_22,

	EN_KER_GPIO_GPB_23,
	EN_KER_GPIO_GPB_24,

	EN_KER_GPIO_GPB_END = EN_KER_GPIO_GPB_24,


	EN_KER_GPIO_GPC_0,
	EN_KER_GPIO_GPC_START = EN_KER_GPIO_GPC_0,
	EN_KER_GPIO_GPC_1,
	EN_KER_GPIO_GPC_2,
	EN_KER_GPIO_GPC_3,
	EN_KER_GPIO_GPC_4,
	EN_KER_GPIO_GPC_5,
	EN_KER_GPIO_GPC_6,
	EN_KER_GPIO_GPC_7,
	EN_KER_GPIO_GPC_8,
	EN_KER_GPIO_GPC_9,
	EN_KER_GPIO_GPC_10,
	EN_KER_GPIO_GPC_11,
	EN_KER_GPIO_GPC_12,
	EN_KER_GPIO_GPC_13,
	EN_KER_GPIO_GPC_14,
	EN_KER_GPIO_GPC_15,
	EN_KER_GPIO_GPC_16,
	EN_KER_GPIO_GPC_17,
	EN_KER_GPIO_GPC_18,
	EN_KER_GPIO_GPC_19,
	EN_KER_GPIO_GPC_20,
	EN_KER_GPIO_GPC_END = EN_KER_GPIO_GPC_20,

	EN_KER_GPIO_GPD_0,
	EN_KER_GPIO_GPD_START = EN_KER_GPIO_GPD_0,
	EN_KER_GPIO_GPD_1,
	EN_KER_GPIO_GPD_2,
	EN_KER_GPIO_GPD_3,
	EN_KER_GPIO_GPD_4,
	EN_KER_GPIO_GPD_5,
	EN_KER_GPIO_GPD_6,
	EN_KER_GPIO_GPD_7,
	EN_KER_GPIO_GPD_8,
	EN_KER_GPIO_GPD_9,
	EN_KER_GPIO_GPD_10,
	EN_KER_GPIO_GPD_11,
	EN_KER_GPIO_GPD_12,
	EN_KER_GPIO_GPD_13,
	EN_KER_GPIO_GPD_14,
	EN_KER_GPIO_GPD_15,
	EN_KER_GPIO_GPD_16,
	EN_KER_GPIO_GPD_17,
	EN_KER_GPIO_GPD_18,
	EN_KER_GPIO_GPD_19,

	EN_KER_GPIO_GPD_20,
	EN_KER_GPIO_GPD_21,
	EN_KER_GPIO_GPD_22,
	EN_KER_GPIO_GPD_23,
	EN_KER_GPIO_GPD_24,
	EN_KER_GPIO_GPD_25,
	EN_KER_GPIO_GPD_26,
	EN_KER_GPIO_GPD_27,
	EN_KER_GPIO_GPD_28,
	EN_KER_GPIO_GPD_29,
	EN_KER_GPIO_GPD_30,
	EN_KER_GPIO_GPD_31,
	EN_KER_GPIO_GPD_END = EN_KER_GPIO_GPD_31,



	EN_KER_GPIO_GPE_0,
	EN_KER_GPIO_GPE_START = EN_KER_GPIO_GPE_0,
	EN_KER_GPIO_GPE_1,
	EN_KER_GPIO_GPE_2,
	EN_KER_GPIO_GPE_3,
	EN_KER_GPIO_GPE_4,
	EN_KER_GPIO_GPE_5,
	EN_KER_GPIO_GPE_6,
	EN_KER_GPIO_GPE_7,
	EN_KER_GPIO_GPE_8,
	EN_KER_GPIO_GPE_9,
	EN_KER_GPIO_GPE_10,
	EN_KER_GPIO_GPE_11,
	EN_KER_GPIO_GPE_12,
	EN_KER_GPIO_GPE_13,
	EN_KER_GPIO_GPE_14,
	EN_KER_GPIO_GPE_15,
	EN_KER_GPIO_GPE_16,
	EN_KER_GPIO_GPE_17,
	EN_KER_GPIO_GPE_18,
	EN_KER_GPIO_GPE_19,
	EN_KER_GPIO_GPE_20,
	EN_KER_GPIO_GPE_21,
	EN_KER_GPIO_GPE_22,
	EN_KER_GPIO_GPE_23,
	EN_KER_GPIO_GPE_24,
	EN_KER_GPIO_GPE_END = EN_KER_GPIO_GPE_24,

	EN_KER_GPIO_PIN_TOTAL,
	EN_KER_GPIO_PIN_NULL = EN_KER_GPIO_PIN_TOTAL,

	EN_KER_GPIO_GPA_NUM = (EN_KER_GPIO_GPA_END - EN_KER_GPIO_GPA_START + 1),
	EN_KER_GPIO_GPB_NUM = (EN_KER_GPIO_GPB_END - EN_KER_GPIO_GPB_START + 1),
	EN_KER_GPIO_GPC_NUM = (EN_KER_GPIO_GPC_END - EN_KER_GPIO_GPC_START + 1),
	EN_KER_GPIO_GPD_NUM = (EN_KER_GPIO_GPD_END - EN_KER_GPIO_GPD_START + 1),
	EN_KER_GPIO_GPE_NUM = (EN_KER_GPIO_GPE_END - EN_KER_GPIO_GPE_START + 1),

};
struct ST_GPIO_MUX_SELECT {
	unsigned int stu32GPA_MUX[EN_KER_GPIO_GPA_NUM][EN_GPIO_MUX_SELECT_MAX];
	unsigned int stu32GPB_MUX[EN_KER_GPIO_GPB_NUM][EN_GPIO_MUX_SELECT_MAX];
	unsigned int stu32GPC_MUX[EN_KER_GPIO_GPC_NUM][EN_GPIO_MUX_SELECT_MAX];
	unsigned int stu32GPD_MUX[EN_KER_GPIO_GPD_NUM][EN_GPIO_MUX_SELECT_MAX];
	unsigned int stu32GPE_MUX[EN_KER_GPIO_GPE_NUM][EN_GPIO_MUX_SELECT_MAX];
};

struct ST_KER_GPIO_INIT_PARAM {
	unsigned int u32GPIOMode[EN_KER_MIPS_GPIO_GROUP_MIPS_MAX];
	unsigned int u32Direction[EN_KER_MIPS_GPIO_GROUP_MIPS_MAX];
	unsigned int u32Level[EN_KER_MIPS_GPIO_GROUP_MIPS_MAX];
	unsigned int u32ActiveMode[EN_KER_MIPS_GPIO_GROUP_MIPS_MAX];
};

struct ST_KER_GPIO_ALT_INIT {
	enum EN_KER_GPIO_PIN	enPin;
	unsigned char			u8enMode;
};

enum EN_KER_GPIO_RMIICLK {
	EN_KER_GPIO_RMIICLK_ORG,
	EN_KER_GPIO_RMIICLK_I2SWS2,
};

struct ST_KER_GPIO_RMIICLK_PARAM {
	unsigned int	u32RMIIREFCLK;
};

struct ST_KER_GPIO_OP_PARAM {
	enum EN_KER_GPIO_PIN enPin;
	union {
		bool b8Value;
		unsigned char u8Value;
	};
};

struct ST_KER_GPIO_MAP_PARAM {
	unsigned char u8IOCount;
	unsigned char u8IOTbl[EN_KER_GPIO_PIN_TOTAL];

};

struct ST_KER_GPIO_OP_FUN_INIT {
	unsigned int ulCount;
	struct ST_KER_GPIO_ALT_INIT *pstGPIOAltInit;
};

#define GPIO_PAD_DRIVING_MASK_BIT (BIT_0 | BIT_1)

enum EN_KER_GPIO_PAD_CFG {
	EN_KER_GPIO_PAD_CFG_DEFAULT_SETTING = 0x8000,
	EN_KER_GPIO_PAD_CFG_PULL_UP = 0x4000,
	EN_KER_GPIO_PAD_CFG_PULL_DOWN = 0x2000,
	EN_KER_GPIO_PAD_CFG_SLEW_RATE = 0x1000,
	EN_KER_GPIO_PAD_CFG_SCHMITT_TRIGGER = 0x0800,
	EN_KER_GPIO_PAD_CFG_IDDQ_TEST_MODE = 0x0400,
	EN_KER_GPIO_PAD_CFG_DRIVING = 0x0200,

	EN_KER_GPIO_PAD_CFG_EN_PULL_UP = 0x40,
	EN_KER_GPIO_PAD_CFG_DIS_PULL_UP = 0x00,

	EN_KER_GPIO_PAD_CFG_EN_PULL_DOWN = 0x20,
	EN_KER_GPIO_PAD_CFG_DIS_PULL_DOWN = 0x00,

	EN_KER_GPIO_PAD_CFG_SLOW_SLEW_RATE = 0x10,
	EN_KER_GPIO_PAD_CFG_FAST_SLEW_RATE = 0x00,

	EN_KER_GPIO_PAD_CFG_EN_SCHMITT_TRIGGER = 0x08,
	EN_KER_GPIO_PAD_CFG_DIS_SCHMITT_TRIGGER = 0x00,

	EN_KER_GPIO_PAD_CFG_EN_IDDQ_TEST_MODE = 0x04,
	EN_KER_GPIO_PAD_CFG_DIS_IDDQ_TEST_MODE = 0x00,

	EN_KER_GPIO_PAD_CFG_DRIVING_10_0mA = 0x03,
	EN_KER_GPIO_PAD_CFG_DRIVING_7_5mA = 0x02,
	EN_KER_GPIO_PAD_CFG_DRIVING_5_0mA = 0x01,
	EN_KER_GPIO_PAD_CFG_DRIVING_2_5mA = 0x00

};

struct ST_KER_GPIO_PAD_PARAM {
	enum EN_KER_GPIO_PIN enPin;
	unsigned short u16Mode;
};

enum EN_KER_GPIO_ALT_MODE {
	EN_KER_GPIO_ALT_MODE_GPIO,
	EN_KER_GPIO_ALT_MODE_ALTERNATIVE,
	EN_KER_GPIO_ALT_MODE_FUN1 = EN_KER_GPIO_ALT_MODE_ALTERNATIVE,
	EN_KER_GPIO_ALT_MODE_FUN2,
	EN_KER_GPIO_ALT_MODE_FUN3,
	EN_KER_GPIO_ALT_MODE_FUN4,
	EN_KER_GPIO_ALT_MODE_FUN5,
	EN_KER_GPIO_ALT_MODE_FUN6,
	EN_KER_GPIO_ALT_MODE_FUN7,

	EN_KER_GPIO_ALT_MODE_TOTAL,
};

enum EN_KER_GPIO_INT_TYPE {
	EN_KER_GPIO_NO_INT = 0,
	EN_KER_GPIO_FALLING_EDGE_INT,
	EN_KER_GPIO_RISING_EDGE_INT,
	EN_KER_GPIO_LOW_LEVEL_INT,
	EN_KER_GPIO_HIGH_LEVEL_INT
};

enum EN_KER_GPIO_DIRECTION {
	EN_KER_GPIO_DIRECTION_INPUT,
	EN_KER_GPIO_DIRECTION_OUTPUT,

	EN_KER_GPIO_DIRECTION_TOTAL
};

enum EN_KER_GPIO_LEVEL {
	EN_KER_GPIO_LEVEL_HIGH,
	EN_KER_GPIO_LEVEL_LOW,
	EN_KER_GPIO_LEVEL_NONE,

	EN_KER_GPIO_LEVEL_TOTAL
};

struct ST_KER_GPIO_INT_PARAM {
	enum EN_KER_GPIO_PIN	enPin;
	enum EN_KER_GPIO_INT_TYPE enIntType;
};

struct ST_KER_GPIO_FUN_PIN_NAME_PARAM {
	enum EN_KER_GPIO_PIN	enPin;
	enum EN_KER_GPIO_ALT_MODE enGpioFun_mode;
	char enGpio_mode[24];
	char enNormal[24];
	char enActive[24];
	char enPad_info[24];
	char enInt_type[24];
	const char *enName;
	bool       b8level;
	bool       b8Direction;
	unsigned char u8FunMode;

};


/* ********************************/

/*  Function Name: ntgpio_ActMemBusSel */

/*  Description:   select active memory bus */

/*  Parameters:    busmode - */

/*  Returns:       TRUE if successful */
/*                 FALSE if fail */

/* ****************************/
extern int  ntgpio_ActMemBusSel(unsigned char busmode);

/* ****************************/

/*  Function Name: ntgpio_OpenGPIO */

/*  Description:   open gpio pin */

/*  Parameters:    pin - pin id */
/*                 gpiomode - TRUE : gpio mode */
/*                            FALSE : alternative mode */

/*  Returns:       TRUE if successful */
/*                 FALSE if fail */

/* ****************************/
/* extern int	ntgpio_OpenGPIO( EN_KER_GPIO_PIN pin, bool gpiomode ); */

/* ****************************/

/*  Function Name: ntgpio_CloseGPIO */

/*  Description:   close gpio pin */

/*  Parameters:    pin - pin id */

/*  Returns:       none */

/* ****************************/


#define GPIOOpen(x) /*  null */
#define GPIOClose(x) /*  null */

#define GPIOActMemBusSel(x)  ntgpio_ActMemBusSel(x)

#define AGPIO0SetA0Selt(x) /*  null */

int  KER_GPIO_DrvInit(void);
void KER_GPIO_DrvExit(void);

int __init nt726xx_gpio_init(void);
void __exit nt726xx_gpio_exit(void);

int nt726xx_gpio_request(struct gpio_chip *chip, unsigned offset);
void nt726xx_gpio_free(struct gpio_chip *chip, unsigned offset);
int nt726xx_gpio_direction_in(struct gpio_chip *chip, unsigned offset);
int nt726xx_gpio_direction_out(struct gpio_chip *chip,
	unsigned offset, int value);
int nt726xx_gpio_get(struct gpio_chip *chip, unsigned offset);
void nt726xx_gpio_set(struct gpio_chip *chip, unsigned offset, int value);

int nt726xx_pinctrl_get(struct gpio_chip *chip, unsigned offset);
int nt726xx_pinctrl_set(struct gpio_chip *chip, unsigned offset, int value);

int nt726xx_ConfigPadMode_set(struct gpio_chip *chip,
	unsigned offset, int value);

void gpio_IOMuxSel(enum EN_KER_GPIO_PIN pin, unsigned int *pData);
static bool gpio_default_function_pin_search(enum EN_KER_GPIO_PIN enPin);

void Control_amp_nreset_inorout(unsigned char inorout);
void Control_amp_nreset_Low(void);
void Control_amp_nreset_High(void);






#endif /* _UIO_NTGPIO_H END */
