#
# Makefile for USB Core files and filesystem
#
usb_snapshot-y := priority_devconfig.o
usb_snapshot-y += kthreadapi.o
usb_snapshot-y += snapshot.o
obj-$(CONFIG_SAMSUNG_USB_PARALLEL_RESUME) +=usb_snapshot.o

