#!/bin/bash

make_product_config_file()
{
	RELEASE_DEF_CONFIG=$1

	perl -pi -e 's/CONFIG_RELAY=y/# CONFIG_RELAY is not set/g' $RELEASE_DEF_CONFIG
	perl -pi -e 's/CONFIG_KALLSYMS=y/# CONFIG_KALLSYMS is not set/g' $RELEASE_DEF_CONFIG
	perl -pi -e 's/CONFIG_PERF_EVENTS=y/# CONFIG_PERF_EVENTS is not set/g' $RELEASE_DEF_CONFIG
	perl -pi -e 's/CONFIG_PROFILING=y/# CONFIG_PROFILING is not set/g' $RELEASE_DEF_CONFIG
	perl -pi -e 's/CONFIG_KPROBES=y/# CONFIG_KPROBES is not set/g' $RELEASE_DEF_CONFIG
	perl -pi -e 's/CONFIG_SPLIT_PTLOCK_CPUS=999999/CONFIG_SPLIT_PTLOCK_CPUS=4/g' $RELEASE_DEF_CONFIG
	perl -pi -e 's/CONFIG_CC_STACKPROTECTOR=y/# CONFIG_CC_STACKPROTECTOR is not set/g' $RELEASE_DEF_CONFIG
	perl -pi -e 's/CONFIG_USB_DEBUG=y/# CONFIG_USB_DEBUG is not set/g' $RELEASE_DEF_CONFIG
	perl -pi -e 's/CONFIG_USB_ANNOUNCE_NEW_DEVICES=y/# CONFIG_USB_ANNOUNCE_NEW_DEVICES is not set/g' $RELEASE_DEF_CONFIG
	perl -pi -e 's/CONFIG_SCSI_LOGGING=y/# CONFIG_SCSI_LOGGING is not set/g' $RELEASE_DEF_CONFIG
	perl -pi -e 's/CONFIG_EMMCFS_DEBUG=y/# CONFIG_EMMCFS_DEBUG is not set/g' $RELEASE_DEF_CONFIG
	perl -pi -e 's/CONFIG_NETWORK_FILESYSTEMS=y/# CONFIG_NETWORK_FILESYSTEMS is not set/g' $RELEASE_DEF_CONFIG
	perl -pi -e 's/CONFIG_PRINTK_TIME=y/# CONFIG_PRINTK_TIME is not set/g' $RELEASE_DEF_CONFIG
	perl -pi -e 's/CONFIG_HEADERS_CHECK=y/# CONFIG_HEADERS_CHECK is not set/g' $RELEASE_DEF_CONFIG
	perl -pi -e 's/CONFIG_LOCKUP_DETECTOR=y/# CONFIG_LOCKUP_DETECTOR is not set/g' $RELEASE_DEF_CONFIG
	perl -pi -e 's/CONFIG_DEBUG_SPINLOCK=y/# CONFIG_DEBUG_SPINLOCK is not set/g' $RELEASE_DEF_CONFIG
	perl -pi -e 's/CONFIG_DEBUG_INFO=y/# CONFIG_DEBUG_INFO is not set/g' $RELEASE_DEF_CONFIG
	perl -pi -e 's/CONFIG_FTRACE=y/# CONFIG_FTRACE is not set/g' $RELEASE_DEF_CONFIG
	perl -pi -e 's/CONFIG_DEBUG_USER=y/# CONFIG_DEBUG_USER is not set/g' $RELEASE_DEF_CONFIG
	perl -pi -e 's/# CONFIG_MOUNT_SECURITY is not set/CONFIG_MOUNT_SECURITY=y/g' $RELEASE_DEF_CONFIG
	perl -pi -e 's/CONFIG_SERIAL_INPUT_ENABLE_HELP_MSG=y/# CONFIG_SERIAL_INPUT_ENABLE_HELP_MSG is not set/g' $RELEASE_DEF_CONFIG
	perl -pi -e 's/CONFIG_KDEBUGD=y/# CONFIG_KDEBUGD is not set/g' $RELEASE_DEF_CONFIG
	perl -pi -e 's/CONFIG_DEBUG_STACKOVERFLOW=y/# CONFIG_DEBUG_STACKOVERFLOW is not set/g' $RELEASE_DEF_CONFIG
	perl -pi -e 's/CONFIG_IRQ_TIME=y/# CONFIG_IRQ_TIME is not set/g' $RELEASE_DEF_CONFIG
	perl -pi -e 's/CONFIG_OPEN_FILE_CHECKER=y/# CONFIG_OPEN_FILE_CHECKER is not set/g' $RELEASE_DEF_CONFIG
	perl -pi -e 's/CONFIG_CRYPTO_DEFLATE=y/# CONFIG_CRYPTO_DEFLATE is not set/g' $RELEASE_DEF_CONFIG
	perl -pi -e 's/CONFIG_BINARY_PRINTF=y/# CONFIG_BINARY_PRINTF is not set/g' $RELEASE_DEF_CONFIG
	perl -pi -e 's/# CONFIG_VD_RELEASE is not set/CONFIG_VD_RELEASE=y/g' $RELEASE_DEF_CONFIG
	perl -pi -e 's/CONFIG_DEBUG_KERNEL=y/# CONFIG_DEBUG_KERNEL is not set/g' $RELEASE_DEF_CONFIG
	perl -pi -e 's/CONFIG_CRYPTO=y/# CONFIG_CRYPTO is not set/g' $RELEASE_DEF_CONFIG
	perl -pi -e 's/CONFIG_HW_PERF_EVENTS=y/# CONFIG_HW_PERF_EVENTS is not set/g' $RELEASE_DEF_CONFIG
	perl -pi -e 's/CONFIG_KALLSYMS_ALL=y/# CONFIG_KALLSYMS_ALL is not set/g' $RELEASE_DEF_CONFIG
	perl -pi -e 's/CONFIG_VM_EVENT_COUNTERS=y/# CONFIG_VM_EVENT_COUNTERS is not set/g' $RELEASE_DEF_CONFIG
	perl -pi -e 's/CONFIG_IOSCHED_DEADLINE=y/# CONFIG_IOSCHED_DEADLINE is not set/g' $RELEASE_DEF_CONFIG
	perl -pi -e 's/CONFIG_ORSAY_DEBUG=y/# CONFIG_ORSAY_DEBUG is not set/g' $RELEASE_DEF_CONFIG
		
	echo -e "\n# CONFIG_UIDGID_STRICT_TYPE_CHECKS is not set" >> $RELEASE_DEF_CONFIG
	echo -e "\nCONFIG_ENABLE_OOM_DEBUG_LOGS=y" >> $RELEASE_DEF_CONFIG

	#############################################################################################
	# For PR
	# LPJ Setting
    #perl -pi -e 's/# CONFIG_LPJ_MANUAL_SETTING is not set/CONFIG_LPJ_MANUAL_SETTING=y\nCONFIG_LPJ_VALUE=96000/g' $RELEASE_DEF_CONFIG
    #perl -pi -e 's/# CONFIG_LPJ_MANUAL_SETTING is not set/CONFIG_LPJ_MANUAL_SETTING=y\nCONFIG_LPJ_VALUE=3174400/g' $RELEASE_DEF_CONFIG

	# SHUTDOWN & SERIAL_INPUT_ENABLE_ONLY_NUMBER Setting
	perl -pi -e 's/CONFIG_ELF_CORE=y/# CONFIG_ELF_CORE is not set/g' $RELEASE_DEF_CONFIG
	perl -pi -e 's/# CONFIG_SHUTDOWN is not set/CONFIG_SHUTDOWN=y/g' $RELEASE_DEF_CONFIG
	perl -pi -e 's/# CONFIG_SERIAL_INPUT_ENABLE_ONLY_NUMBER is not set/CONFIG_SERIAL_INPUT_ENABLE_ONLY_NUMBER=y/g' $RELEASE_DEF_CONFIG
	#############################################################################################
	
	# TNTFS disable
    perl -pi -e 's/CONFIG_TNTFS_FS=m/# CONFIG_TNTFS_FS is not set/g' $RELEASE_DEF_CONFIG

	# 20131022
	perl -pi -e 's/CONFIG_ALLOW_ALL_USER_COREDUMP=y/# CONFIG_ALLOW_ALL_USER_COREDUMP is not set/g' $RELEASE_DEF_CONFIG
	# 20131205
	perl -pi -e 's/CONFIG_UNHANDLED_IRQ_TRACE_DEBUGGING=y/# CONFIG_UNHANDLED_IRQ_TRACE_DEBUGGING is not set/g' $RELEASE_DEF_CONFIG
	
	# 20131217 Existing Config of the Linux Team
	perl -pi -e 's/CONFIG_BINFMT_ELF_COMP=y/# CONFIG_BINFMT_ELF_COMP is not set/g' $RELEASE_DEF_CONFIG
	perl -pi -e 's/CONFIG_FUNCTION_TRACER=y/# CONFIG_FUNCTION_TRACER is not set/g' $RELEASE_DEF_CONFIG
	perl -pi -e 's/CONFIG_OPROFILE=y/# CONFIG_OPROFILE is not set/g' $RELEASE_DEF_CONFIG
	perl -pi -e 's/CONFIG_RING_BUFFER_ALLOW_SWAP=y/# CONFIG_RING_BUFFER_ALLOW_SWAP is not set/g' $RELEASE_DEF_CONFIG
	perl -pi -e 's/CONFIG_SCHED_TRACER=y/# CONFIG_SCHED_TRACER is not set/g' $RELEASE_DEF_CONFIG
	perl -pi -e 's/CONFIG_STACK_TRACER=y/# CONFIG_STACK_TRACER is not set/g' $RELEASE_DEF_CONFIG
	# 20131217 New Config of the Linux Team
	perl -pi -e 's/CONFIG_BLK_DEV_IO_TRACE=y/# CONFIG_BLK_DEV_IO_TRACE is not set/g' $RELEASE_DEF_CONFIG
	perl -pi -e 's/CONFIG_IRQSOFF_TRACER=y/# CONFIG_IRQSOFF_TRACER is not set/g' $RELEASE_DEF_CONFIG
	perl -pi -e 's/CONFIG_PREEMPT_TRACER=y/# CONFIG_PREEMPT_TRACER is not set/g' $RELEASE_DEF_CONFIG
	perl -pi -e 's/CONFIG_BRANCH_PROFILE_NONE=y/# CONFIG_BRANCH_PROFILE_NONE is not set/g' $RELEASE_DEF_CONFIG
	perl -pi -e 's/CONFIG_CACHE_ANALYZER=y/# CONFIG_CACHE_ANALYZER is not set/g' $RELEASE_DEF_CONFIG
	perl -pi -e 's/CONFIG_CONTEXT_SWITCH_TRACER=y/# CONFIG_CONTEXT_SWITCH_TRACER is not set/g' $RELEASE_DEF_CONFIG
	perl -pi -e 's/CONFIG_DWARF_MODULE=y/# CONFIG_DWARF_MODULE is not set/g' $RELEASE_DEF_CONFIG
	perl -pi -e 's/CONFIG_DYNAMIC_FTRACE=y/# CONFIG_DYNAMIC_FTRACE is not set/g' $RELEASE_DEF_CONFIG
	perl -pi -e 's/CONFIG_ELF_MODULE=y/# CONFIG_ELF_MODULE is not set/g' $RELEASE_DEF_CONFIG
	perl -pi -e 's/CONFIG_EVENT_POWER_TRACING_DEPRECATED=y/# CONFIG_EVENT_POWER_TRACING_DEPRECATED is not set/g' $RELEASE_DEF_CONFIG
	perl -pi -e 's/CONFIG_EVENT_TRACING=y/# CONFIG_EVENT_TRACING is not set/g' $RELEASE_DEF_CONFIG
	perl -pi -e 's/CONFIG_FUNCTION_GRAPH_TRACER=y/# CONFIG_FUNCTION_GRAPH_TRACER is not set/g' $RELEASE_DEF_CONFIG
	perl -pi -e 's/CONFIG_GENERIC_TRACER=y/# CONFIG_GENERIC_TRACER is not set/g' $RELEASE_DEF_CONFIG
	perl -pi -e 's/CONFIG_IRQ_WORK=y/# CONFIG_IRQ_WORK is not set/g' $RELEASE_DEF_CONFIG
	perl -pi -e 's/CONFIG_MEMORY_VALIDATOR=y/# CONFIG_MEMORY_VALIDATOR is not set/g' $RELEASE_DEF_CONFIG
	perl -pi -e 's/CONFIG_NOP_TRACER=y/# CONFIG_NOP_TRACER is not set/g' $RELEASE_DEF_CONFIG
	perl -pi -e 's/CONFIG_RING_BUFFER=y/# CONFIG_RING_BUFFER is not set/g' $RELEASE_DEF_CONFIG
	perl -pi -e 's/CONFIG_SCHED_HISTORY=y/# CONFIG_SCHED_HISTORY is not set/g' $RELEASE_DEF_CONFIG
	perl -pi -e 's/CONFIG_SCHED_TRACER=y/# CONFIG_SCHED_TRACER is not set/g' $RELEASE_DEF_CONFIG
	perl -pi -e 's/CONFIG_SHOW_TASK_PRIORITY=y/# CONFIG_SHOW_TASK_PRIORITY is not set/g' $RELEASE_DEF_CONFIG
	perl -pi -e 's/CONFIG_SHOW_TASK_STATE=y/# CONFIG_SHOW_TASK_STATE is not set/g' $RELEASE_DEF_CONFIG
	perl -pi -e 's/CONFIG_SHOW_USER_MAPS_WITH_PID=y/# CONFIG_SHOW_USER_MAPS_WITH_PID is not set/g' $RELEASE_DEF_CONFIG
	perl -pi -e 's/CONFIG_SHOW_USER_STACK_WITH_PID=y/# CONFIG_SHOW_USER_STACK_WITH_PID is not set/g' $RELEASE_DEF_CONFIG
	perl -pi -e 's/CONFIG_SHOW_USER_THREAD_REGS=y/# CONFIG_SHOW_USER_THREAD_REGS is not set/g' $RELEASE_DEF_CONFIG
	perl -pi -e 's/CONFIG_STACKTRACE=y/# CONFIG_STACKTRACE is not set/g' $RELEASE_DEF_CONFIG
	perl -pi -e 's/CONFIG_TASK_FOR_COREDUMP=y/# CONFIG_TASK_FOR_COREDUMP is not set/g' $RELEASE_DEF_CONFIG
	perl -pi -e 's/CONFIG_TASK_STATE_BACKTRACE=y/# CONFIG_TASK_STATE_BACKTRACE is not set/g' $RELEASE_DEF_CONFIG
	perl -pi -e 's/CONFIG_TRACE_CLOCK=y/# CONFIG_TRACE_CLOCK is not set/g' $RELEASE_DEF_CONFIG
	perl -pi -e 's/CONFIG_TRACE_IRQFLAGS=y/# CONFIG_TRACE_IRQFLAGS is not set/g' $RELEASE_DEF_CONFIG
	perl -pi -e 's/CONFIG_TRACE_THREAD_PC=y/# CONFIG_TRACE_THREAD_PC is not set/g' $RELEASE_DEF_CONFIG
	perl -pi -e 's/CONFIG_TRACEPOINTS=y/# CONFIG_TRACEPOINTS is not set/g' $RELEASE_DEF_CONFIG
	perl -pi -e 's/CONFIG_TRACER_MAX_TRACE=y/# CONFIG_TRACER_MAX_TRACE is not set/g' $RELEASE_DEF_CONFIG
	perl -pi -e 's/CONFIG_TRACING=y/# CONFIG_TRACING is not set/g' $RELEASE_DEF_CONFIG
	perl -pi -e 's/CONFIG_VIRTUAL_TO_PHYSICAL=y/# CONFIG_VIRTUAL_TO_PHYSICAL is not set/g' $RELEASE_DEF_CONFIG
	perl -pi -e 's/CONFIG_OLD_MCOUNT=y/# CONFIG_OLD_MCOUNT is not set/g' $RELEASE_DEF_CONFIG
	perl -pi -e 's/CONFIG_ZRAM_DEBUG=y/# CONFIG_ZRAM_DEBUG is not set/g' $RELEASE_DEF_CONFIG

	# 20140102 
	perl -pi -e 's/CONFIG_PM_BUG_ON_PROBLEM=y/# CONFIG_PM_BUG_ON_PROBLEM is not set/g' $RELEASE_DEF_CONFIG
	
	# 20140114 Disable CONFIG_PRINTK_CPUID for product mode
	perl -pi -e 's/CONFIG_PRINTK_CPUID=y/# CONFIG_PRINTK_CPUID is not set/g' $RELEASE_DEF_CONFIG
	
	# 20140207 Disable CONFIG_DEBUG_OBJECTS, CONFIG_DEBUG_OBJECTS_PERCPU_COUNTER (Only DEBUG mode enable) 
	perl -pi -e 's/CONFIG_DEBUG_OBJECTS=y/# CONFIG_DEBUG_OBJECTS is not set/g' $RELEASE_DEF_CONFIG
	perl -pi -e 's/CONFIG_DEBUG_OBJECTS_PERCPU_COUNTER=y/# CONFIG_DEBUG_OBJECTS_PERCPU_COUNTER is not set/g' $RELEASE_DEF_CONFIG

    # 20141023 Disable config related to VDFS
    perl -pi -e 's/CONFIG_VDFS_POSIX_ACL=y/# CONFIG_VDFS_POSIX_ACL is not set/g' $RELEASE_DEF_CONFIG
    perl -pi -e 's/CONFIG_VDFS_DEBUG=y/# CONFIG_VDFS_DEBUG is not set/g' $RELEASE_DEF_CONFIG
    perl -pi -e 's/CONFIG_VDFS_PANIC_ON_ERROR=y/# CONFIG_VDFS_PANIC_ON_ERROR is not set/g' $RELEASE_DEF_CONFIG
    perl -pi -e 's/CONFIG_VDFS_SW_DECOMPRESS_RETRY=y/# CONFIG_VDFS_SW_DECOMPRESS_RETRY is not set/g' $RELEASE_DEF_CONFIG
    perl -pi -e 's/CONFIG_VDFS_CRC_CHECK=y/# CONFIG_VDFS_CRC_CHECK is not set/g' $RELEASE_DEF_CONFIG

    # 20141029 CONFIG_SLUB_DEBUG=n
    perl -pi -e 's/CONFIG_SLUB_DEBUG=y/# CONFIG_SLUB_DEBUG is not set/g' $RELEASE_DEF_CONFIG

    # 20141030 CONFIG_DEBUG_HIGHMEM=n
    perl -pi -e 's/CONFIG_DEBUG_HIGHMEM=y/# CONFIG_DEBUG_HIGHMEM is not set/g' $RELEASE_DEF_CONFIG

    # 20141031 CONFIG_PAGE_OWNER=n
    perl -pi -e 's/CONFIG_PAGE_OWNER=y/# CONFIG_PAGE_OWNER is not set/g' $RELEASE_DEF_CONFIG

    # 20141103 CONFIG_VD_HMP_DEBUG=n
    perl -pi -e 's/CONFIG_VD_HMP_DEBUG=y/# CONFIG_VD_HMP_DEBUG is not set/g' $RELEASE_DEF_CONFIG

    # 20141110
	# 20150116 CONFIG_MUPT_TRACE=n to debug,perf,product mode in HawkP and HAWKA 
    perl -pi -e 's/CONFIG_MUPT_TRACE=y/# CONFIG_MUPT_TRACE is not set/g' $RELEASE_DEF_CONFIG
    perl -pi -e 's/CONFIG_KDML=y/# CONFIG_KDML is not set/g' $RELEASE_DEF_CONFIG

	# 20141111 CONFIG_OPEN_FILE_CHECKER=y , 20150102 Add HawkM, HAWKA
    perl -pi -e 's/# CONFIG_OPEN_FILE_CHECKER is not set/CONFIG_OPEN_FILE_CHECKER=y/g' $RELEASE_DEF_CONFIG

    # 20141202 CONFIG_VDFS_DEBUG_AUTHENTICAION=n
    perl -pi -e 's/CONFIG_VDFS_DEBUG_AUTHENTICAION=y/# CONFIG_VDFS_DEBUG_AUTHENTICAION is not set/g' $RELEASE_DEF_CONFIG

	# 20141208 CONFIG_MMC_DEBUG_IOCTL=n
    perl -pi -e 's/CONFIG_MMC_DEBUG_IOCTL=y/# CONFIG_MMC_DEBUG_IOCTL is not set/g' $RELEASE_DEF_CONFIG

    # 20141215 CONFIG_PID_IN_CONTEXTIDR=n
    perl -pi -e 's/CONFIG_PID_IN_CONTEXTIDR=y/# CONFIG_PID_IN_CONTEXTIDR is not set/g' $RELEASE_DEF_CONFIG

    # 20141224 CONFIG_CMA_DEBUG=n
    perl -pi -e 's/CONFIG_CMA_DEBUG=y/# CONFIG_CMA_DEBUG is not set/g' $RELEASE_DEF_CONFIG

	# 20141229 CONFIG_MODULES_USE_LONG_CALLS=n
	echo -e "\n# CONFIG_MODULES_USE_LONG_CALLS is not set" >> $RELEASE_DEF_CONFIG

    # 20150217 CONFIG_MINIMAL_CORE=y
    perl -pi -e 's/# CONFIG_MINIMAL_CORE is not set/CONFIG_MINIMAL_CORE=y/g' $RELEASE_DEF_CONFIG
	echo -e "\nCONFIG_MINCORE_RLIMIT_NOFILE=y" >> $RELEASE_DEF_CONFIG

    # 20150217 CONFIG_SECURITY_SFD_MODE_ENFORCE=y, CONFIG_SECURITY_SFD_LEVEL_RELEASE=y
    perl -pi -e 's/CONFIG_SECURITY_SFD_MODE_PERMISSIVE=y/# CONFIG_SECURITY_SFD_MODE_PERMISSIVE is not set/g' $RELEASE_DEF_CONFIG
    perl -pi -e 's/# CONFIG_SECURITY_SFD_MODE_ENFORCE is not set/CONFIG_SECURITY_SFD_MODE_ENFORCE=y/g' $RELEASE_DEF_CONFIG
    perl -pi -e 's/CONFIG_SECURITY_SFD_LEVEL_DEBUG=y/# CONFIG_SECURITY_SFD_LEVEL_DEBUG is not set/g' $RELEASE_DEF_CONFIG
    perl -pi -e 's/# CONFIG_SECURITY_SFD_LEVEL_RELEASE is not set/CONFIG_SECURITY_SFD_LEVEL_RELEASE=y/g' $RELEASE_DEF_CONFIG

	# 20150228
	perl -pi -e 's/CONFIG_USB_RTL8150=m/# CONFIG_USB_RTL8150 is not set/g' $RELEASE_DEF_CONFIG
	perl -pi -e 's/CONFIG_USB_USBNET=m/# CONFIG_USB_USBNET is not set/g' $RELEASE_DEF_CONFIG
	perl -pi -e 's/CONFIG_USB_NET_AX88772=m/# CONFIG_USB_NET_AX88772 is not set/g' $RELEASE_DEF_CONFIG
        # 20150312
        perl -pi -e 's/CONFIG_PHYLIB=y/# CONFIG_PHYLIB is not set/g' $RELEASE_DEF_CONFIG

        # 20150316
        echo -e "\nCONFIG_MINIMAL_CORE_RETAIN=y" >> $RELEASE_DEF_CONFIG
}

make_perf_config_file()
{
	PERF_DEF_CONFIG=$1
	
	make_product_config_file $PERF_DEF_CONFIG

	perl -pi -e 's/CONFIG_SHUTDOWN=y/# CONFIG_SHUTDOWN is not set/g' $PERF_DEF_CONFIG
	perl -pi -e 's/CONFIG_SERIAL_INPUT_ENABLE_ONLY_NUMBER=y/# CONFIG_SERIAL_INPUT_ENABLE_ONLY_NUMBER is not set/g' $PERF_DEF_CONFIG
		
	perl -pi -e 's/# CONFIG_PROFILING is not set/CONFIG_PROFILING=y/g' $PERF_DEF_CONFIG
	perl -pi -e 's/# CONFIG_FTRACE is not set/CONFIG_FTRACE=y/g' $PERF_DEF_CONFIG
	perl -pi -e 's/# CONFIG_HW_PERF_EVENTS is not set/CONFIG_HW_PERF_EVENTS=y/g' $PERF_DEF_CONFIG
	perl -pi -e 's/# CONFIG_PERF_EVENTS is not set/CONFIG_PERF_EVENTS=y/g' $PERF_DEF_CONFIG
	
	# For CONFIG_ENABLE_DEFAULT_TRACERS=y
	perl -pi -e 's/CONFIG_IRQSOFF_TRACER=y/# CONFIG_IRQSOFF_TRACER is not set/g' $PERF_DEF_CONFIG
	perl -pi -e 's/CONFIG_PREEMPT_TRACER=y/# CONFIG_PREEMPT_TRACER is not set/g' $PERF_DEF_CONFIG
	perl -pi -e 's/CONFIG_SCHED_TRACER=y/# CONFIG_SCHED_TRACER is not set/g' $PERF_DEF_CONFIG
	perl -pi -e 's/CONFIG_BLK_DEV_IO_TRACE=y/# CONFIG_BLK_DEV_IO_TRACE is not set/g' $PERF_DEF_CONFIG
	echo -e "\nCONFIG_ENABLE_DEFAULT_TRACERS=y" >> $PERF_DEF_CONFIG

	# TNTFS setting
    perl -pi -e 's/# CONFIG_TNTFS_FS is not set/CONFIG_TNTFS_FS=m/g' $PERF_DEF_CONFIG

	# 20141023 Disable config related to VDFS
	perl -pi -e 's/CONFIG_VDFS_POSIX_ACL=y/# CONFIG_VDFS_POSIX_ACL is not set/g' $PERF_DEF_CONFIG
	perl -pi -e 's/CONFIG_VDFS_DEBUG=y/# CONFIG_VDFS_DEBUG is not set/g' $PERF_DEF_CONFIG
	perl -pi -e 's/CONFIG_VDFS_PANIC_ON_ERROR=y/# CONFIG_VDFS_PANIC_ON_ERROR is not set/g' $PERF_DEF_CONFIG
	perl -pi -e 's/CONFIG_VDFS_SW_DECOMPRESS_RETRY=y/# CONFIG_VDFS_SW_DECOMPRESS_RETRY is not set/g' $PERF_DEF_CONFIG
	perl -pi -e 's/CONFIG_VDFS_CRC_CHECK=y/# CONFIG_VDFS_CRC_CHECK is not set/g' $PERF_DEF_CONFIG

	# 20141029 CONFIG_SLUB_DEBUG=n
	perl -pi -e 's/CONFIG_SLUB_DEBUG=y/# CONFIG_SLUB_DEBUG is not set/g' $PERF_DEF_CONFIG

	# 20141030 CONFIG_DEBUG_HIGHMEM=n
	perl -pi -e 's/CONFIG_DEBUG_HIGHMEM=y/# CONFIG_DEBUG_HIGHMEM is not set/g' $PERF_DEF_CONFIG

	# 20141031 CONFIG_PAGE_OWNER=n
	perl -pi -e 's/CONFIG_PAGE_OWNER=y/# CONFIG_PAGE_OWNER is not set/g' $PERF_DEF_CONFIG

	# 20141103 CONFIG_VD_HMP_DEBUG=n
	perl -pi -e 's/CONFIG_VD_HMP_DEBUG=y/# CONFIG_VD_HMP_DEBUG is not set/g' $PERF_DEF_CONFIG

	# 20141110
	# 20150116 CONFIG_MUPT_TRACE=n to debug,perf,product mode in HawkP and HAWKA
    perl -pi -e 's/CONFIG_MUPT_TRACE=y/# CONFIG_MUPT_TRACE is not set/g' $PERF_DEF_CONFIG
	perl -pi -e 's/CONFIG_KDML=y/# CONFIG_KDML is not set/g' $PERF_DEF_CONFIG
	
    # 20141111 CONFIG_OPEN_FILE_CHECKER=y , 20150102 Add HawkM, HAWKA
    perl -pi -e 's/# CONFIG_OPEN_FILE_CHECKER is not set/CONFIG_OPEN_FILE_CHECKER=y/g' $PERF_DEF_CONFIG

	# 20141202 CONFIG_VDFS_DEBUG_AUTHENTICAION=n
	perl -pi -e 's/CONFIG_VDFS_DEBUG_AUTHENTICAION=y/# CONFIG_VDFS_DEBUG_AUTHENTICAION is not set/g' $PERF_DEF_CONFIG

    # 20141208 CONFIG_MMC_DEBUG_IOCTL=y
    perl -pi -e 's/# CONFIG_MMC_DEBUG_IOCTL is not set/CONFIG_MMC_DEBUG_IOCTL=y/g' $PERF_DEF_CONFIG

	# 20141215 CONFIG_PID_IN_CONTEXTIDR=n
    perl -pi -e 's/CONFIG_PID_IN_CONTEXTIDR=y/# CONFIG_PID_IN_CONTEXTIDR is not set/g' $PERF_DEF_CONFIG

	# 20141224 CONFIG_CMA_DEBUG=n
    perl -pi -e 's/CONFIG_CMA_DEBUG=y/# CONFIG_CMA_DEBUG is not set/g' $PERF_DEF_CONFIG

    # 20150217 CONFIG_MINIMAL_CORE=y
    perl -pi -e 's/# CONFIG_MINIMAL_CORE is not set/CONFIG_MINIMAL_CORE=y\nCONFIG_MINCORE_RLIMIT_NOFILE=y/g' $PERF_DEF_CONFIG
	echo -e "\nCONFIG_MINCORE_RLIMIT_NOFILE=y" >> $PERF_DEF_CONFIG

    # 20150217 CONFIG_SECURITY_SFD_MODE_ENFORCE=y, CONFIG_SECURITY_SFD_LEVEL_RELEASE=y
    perl -pi -e 's/CONFIG_SECURITY_SFD_MODE_PERMISSIVE=y/# CONFIG_SECURITY_SFD_MODE_PERMISSIVE is not set/g' $PERF_DEF_CONFIG
    perl -pi -e 's/# CONFIG_SECURITY_SFD_MODE_ENFORCE is not set/CONFIG_SECURITY_SFD_MODE_ENFORCE=y/g' $PERF_DEF_CONFIG
    perl -pi -e 's/CONFIG_SECURITY_SFD_LEVEL_DEBUG=y/# CONFIG_SECURITY_SFD_LEVEL_DEBUG is not set/g' $PERF_DEF_CONFIG
    perl -pi -e 's/# CONFIG_SECURITY_SFD_LEVEL_RELEASE is not set/CONFIG_SECURITY_SFD_LEVEL_RELEASE=y/g' $PERF_DEF_CONFIG

        # 20150228
        perl -pi -e 's/CONFIG_USB_RTL8150=m/# CONFIG_USB_RTL8150 is not set/g' $PERF_DEF_CONFIG
        perl -pi -e 's/CONFIG_USB_USBNET=m/# CONFIG_USB_USBNET is not set/g' $PERF_DEF_CONFIG
        perl -pi -e 's/CONFIG_USB_NET_AX88772=m/# CONFIG_USB_NET_AX88772 is not set/g' $PERF_DEF_CONFIG
       
        # 20150312
        perl -pi -e 's/CONFIG_PHYLIB=y/# CONFIG_PHYLIB is not set/g' $PERF_DEF_CONFIG
        
        # 20150316
        perl -pi -e 's/CONFIG_MINIMAL_CORE_RETAIN=y/# CONFIG_MINIMAL_CORE_RETAIN is not set/g' $PERF_DEF_CONFIG
}	

MODEL_TARGET=$1
CONFIG_PATH=arch/arm/configs
echo "Do you want to make latest product & perf config of $MODEL_TARGET? [y/n]"
read answer

if [ $answer == "y" ]
then
    sudo cp "$CONFIG_PATH"/"$MODEL_TARGET"_debug_defconfig "$CONFIG_PATH"/"$MODEL_TARGET"_release_defconfig
    chmod +rw "$CONFIG_PATH"/"$MODEL_TARGET"_release_defconfig
    make_product_config_file "$CONFIG_PATH"/"$MODEL_TARGET"_release_defconfig
    mv .config .config_tmp

    cp "$CONFIG_PATH"/"$MODEL_TARGET"_release_defconfig .config
    make oldconfig
    cp .config "$CONFIG_PATH"/"$MODEL_TARGET"_release_defconfig

    sudo cp "$CONFIG_PATH"/"$MODEL_TARGET"_debug_defconfig "$CONFIG_PATH"/"$MODEL_TARGET"_perf_defconfig
    chmod +rw "$CONFIG_PATH"/"$MODEL_TARGET"_perf_defconfig
    make_perf_config_file "$CONFIG_PATH"/"$MODEL_TARGET"_perf_defconfig

    cp "$CONFIG_PATH"/"$MODEL_TARGET"_perf_defconfig .config
    make oldconfig
    cp .config "$CONFIG_PATH"/"$MODEL_TARGET"_perf_defconfig
    mv .config_tmp .config
fi

