/**\file
 *  To distinguish different manufacture
 * \internal
 * ----------------------------REVISION HISTORY-----------------------------
 * NVT			2016/0205       SamKuo
 */


#ifndef _CPE_H_
#define _CPE_H_

enum en_cpe_trimdata_type {
	EN_CPE_TRIMDATA_TYPE_VDAC,
	EN_CPE_TRIMDATA_TYPE_HDMIMHL,
	EN_CPE_TRIMDATA_TYPE_LVDS,
	EN_CPE_TRIMDATA_TYPE_USB01,
	EN_CPE_TRIMDATA_TYPE_ETH_CURRENT,
	EN_CPE_TRIMDATA_TYPE_ETH_RESISTANCE,
	EN_CPE_TRIMDATA_TYPE_USB23,
	EN_CPE_TRIMDATA_TYPE_MAX,
};
enum en_prod_opt {
	EN_VDAC_TRIM1_VALID = 0,
	EN_HDMI_RX_TRIM1_VALID,
	EN_LVDS_TX_TRIM1_VALID,
	EN_USB_01_TRIM1_VALID,
	EN_ETHERNET_TRIM1_VALID,
	EN_VDAC_TRIM2_VALID,
	EN_HDMI_RX_TRIM2_VALID,
	EN_LVDS_TX_TRIM2_VALID,

	EN_USB_01_TRIM2_VALID,
	EN_ETHERNET_TRIM2_VALID,
	EN_VDAC_TRIM3_VALID,
	EN_HDMI_RX_TRIM3_VALID,
	EN_LVDS_TX_TRIM3_VALID,
	EN_USB_01_TRIM3_VALID,
	EN_ETHERNET_TRIM3_VALID,
	EN_TRAN_SEL,

	EN_MID1_VALID,
	EN_MID2_VALID,
	EN_MID3_VALID,
	EN_MID4_VALID,
	EN_USB23_TRIM1_VALID,
	EN_USB23_TRIM2_VALID,
	EN_USB23_TRIM3_VALID,
	EN_ETH_RESISTANCE_TRIM1_VALID,

	EN_ETH_RESISTANCE_TRIM2_VALID,
	EN_ETH_RESISTANCE_TRIM3_VALID,
	EN_USB_TRIM_EN,

	EN_DVB_S2_SW_DIS,
	EN_DVB_T2_SW_DIS,
	EN_DVB_DTMB_SW_DIS,
};
union _st_trim {
	struct {
		u8  TRIM1_VDAC;
		u8  TRIM1_HDMI_RX[2];
		u8  TRIM1_LVDS_TX;
		u8  TRIM1_USB_01:5;
		u8  TRIM1_USB_01_Reserved:3;
		u8  TRIM1_ETH_CURRENT:6;
		u8  TRIM1_ETH_CURRENT_Reserved:2;
		u8  TRIM1_ETH_RESISTANCE;
		u8  TRIM1_USB_PORT23:5;
		u8  TRIM1_USB_PORT23_Reserved:3;


		u8  TRIM2_VDAC;
		u8  TRIM2_HDMI_RX[2];
		u8  TRIM2_LVDS_TX;
		u8  TRIM2_USB_01:5;
		u8  TRIM2_USB_01_Reserved:3;
		u8  TRIM2_ETH_CURRENT:6;
		u8  TRIM2_ETH_CURRENT_Reserved:2;
		u8  TRIM2_ETH_RESISTANCE;
		u8  TRIM2_USB_PORT23:5;
		u8  TRIM2_USB_PORT23_Reserved:3;


		u8  TRIM3_VDAC;
		u8  TRIM3_HDMI_RX[2];
		u8  TRIM3_LVDS_TX;
		u8  TRIM3_USB_01:5;
		u8  TRIM3_USB_01_Reserved:3;
		u8  TRIM3_ETH_CURRENT:6;
		u8  TRIM3_ETH_CURRENT_Reserved:2;
		u8  TRIM3_ETH_RESISTANCE;
		u8  TRIM3_USB_PORT23:5;
		u8  TRIM3_USB_PORT23_Reserved:3;
	} DATA;
	u32 u32Trim[6]; /* total 24 bytes */
};

union _st_prod_opt {
	struct {
		u8 VDAC_TRIM1_VALID:1;
		u8 HDMI_RX_TRIM1_VALID:1;
		u8 LVDS_TX_TRIM1_VALID:1;
		u8 USB_01_TRIM1_VALID:1;
		u8 ETH_CURRENT_TRIM1_VALID:1;
		u8 VDAC_TRIM2_VALID:1;
		u8 HDMI_RX_TRIM2_VALID:1;
		u8 LVDS_TX_TRIM2_VALID:1;

		u8 USB_01_TRIM2_VALID:1;
		u8 ETH_CURRENT_TRIM2_VALID:1;
		u8 VDAC_TRIM3_VALID:1;
		u8 HDMI_RX_TRIM3_VALID:1;
		u8 LVDS_TX_TRIM3_VALID:1;
		u8 USB_01_TRIM3_VALID:1;
		u8 ETH_CURRENT_TRIM3_VALID:1;
		u8 TRAN_SEL:1;

		u8 MID1_VALID:1;
		u8 MID2_VALID:1;
		u8 MID3_VALID:1;
		u8 MID4_VALID:1;
		u8 USB_PORT23_TRIM1_VALID:1;
		u8 USB_PORT23_TRIM2_VALID:1;
		u8 USB_PORT23_TRIM3_VALID:1;
		u8 ETH_RESISTANCE_TRIM1_VALID:1;

		u8 ETH_RESISTANCE_TRIM2_VALID:1;
		u8 ETH_RESISTANCE_TRIM3_VALID:1;
		u8 USB_TRIM_EN:1;
		u8 Reserved:5;

		u8 DVB_S2_SW_DIS:1;
		u8 DVB_T2_SW_DIS:1;
		u8 DVB_DTMB_SW_DIS:1;
		u8 TCON_OPT:1;
		u8 TRAN1_RESERVED:4;
	} ST_U8bit;
	u8 ST_U8[5];
};
int ntcpe_read_valid_bit(enum en_prod_opt en_valid_type);
int ntcpe_read_trimdata(enum en_cpe_trimdata_type entype);
#endif
