obj-y	+= common.o
obj-y	+= sdp_hwmem.o
obj-y	+= sdp_kade.o

#SDP UNZIP
obj-$(CONFIG_SDP_UNZIP)         += sdp_unzip.o
obj-$(CONFIG_SDP_UNZIP_TEST)            += sdp_unzip_test.o
obj-$(CONFIG_SDP_UNZIP_HWDCOMP_VDFS)	+= sdp_unzip_vdfsapi.o

obj-$(CONFIG_SDP_MICOM_PINCTRL)	+= sdp_micom_pinctrl.o

#SPI
obj-$(CONFIG_SDP_SPI)           += sdp_spi.o
obj-$(CONFIG_SDP_SPIDEV)        += sdp_spidev.o

obj-$(CONFIG_SDP_THERMAL)	+= sdp_thermal.o
obj-$(CONFIG_SDP_BUS_ERR_LOGGER)	+= sdp_bus_err_logger.o
obj-$(CONFIG_SDP_DEV_PM)	+= sdp_dev_pm.o
