/*
 * tvis_agent_cmds.h
 *
 * Copyright (C) 2012 Samsung Electronics
 *
 * NOTE:
 *
 */
#ifndef _TVIS_AGENT_CMDS_H
#define _TVIS_AGENT_CMDS_H

enum tvis_agent_kdbg_cm_event{
	START,
	STOP
};

/* kdebugd commands */
enum tvis_agent_kdbg_cmds {

	KDBG_CMD_START_KDEBUGD = 0x00000001,
	KDBG_CMD_STOP_KDEBUGD,
	KDBG_CMD_GET_THREAD_INFO,
	KDBG_CMD_GET_MEM_USAGE,
	KDBG_CMD_CM_CPU_USAGE,
	KDBG_CMD_CM_THREAD_USAGE,
	KDBG_CMD_CM_PROCESS_USAGE,
	KDBG_CMD_CM_PHY_MEM_USAGE,
	KDBG_CMD_GET_VIRT_MEM_USAGE,
	KDBG_CMD_CM_PMU_CNTR = 0x0000000A,
	KDBG_CMD_CM_DISK_USAGE,
	KDBG_CMD_CM_NET_USAGE,
	KDBG_CMD_AOP_GET_SRC,
	KDBG_CMD_AOP_SET_SRC,
	KDBG_CMD_AOP_START,
	KDBG_CMD_AOP_STOP = 0x00000010,
	KDBG_CMD_AOP_DATA,
	KDBG_CMD_AOP_DATA_END,
	KDBG_CMD_GET_THREAD_INFO_DETAIL,
	KDBG_CMD_START_THREAD_PROFILE_INFO,
	KDBG_CMD_THREAD_PROFILE_INFO,
	KDBG_CMD_STOP_THREAD_PROFILE_INFO,
	KDBG_CMD_CM_MEM_INFO,
	KDBG_CMD_KDML_GET_ALLOCS_SUMMARY = 0x00000019,
	KDBG_CMD_KDML_ALLOCS_SUMMARY_START,
	KDBG_CMD_KDML_ALLOCS_SUMMARY_CONT,
	KDBG_CMD_KDML_ALLOCS_SUMMARY_END,
	KDBG_CMD_KDML_MODULE_START,
	KDBG_CMD_KDML_MODULE_END,
	KDBG_CMD_KDML_GET_SLABINFO,
	KDBG_CMD_KDML_SLABINFO_START,
	KDBG_CMD_KDML_SLABINFO_CONT,
	KDBG_CMD_KDML_SLABINFO_END,
	KDBG_CMD_KDML_START_STOP,
	KDBG_CMD_CM_FD_INFO = 0x00000031,
	KDBG_CMD_CM_FD_INFO_START,
	KDBG_CMD_CM_FD_INFO_CONT,
	KDBG_CMD_CM_FD_INFO_END,
	KDBG_CMD_CM_FD_GET_DETAIL,
	KDBG_CMD_CM_FD_DETAIL_START,
	KDBG_CMD_CM_FD_DETAIL_CONT,
	KDBG_CMD_CM_FD_DETAIL_END,
	KDBG_CMD_CM_PSS_MEM_USAGE,
	KDBG_CMD_PROC_FD_BT,
	KDBG_CMD_CM_STACK_SIZE_TRACER = 0x0000003D,
	KDBG_CMD_CM_STACK_SIZE_TRACER_START,
	KDBG_CMD_CM_STACK_SIZE_TRACER_CONT,
	KDBG_CMD_CM_STACK_SIZE_TRACER_END,
	KDBG_CMD_MAX = 0x00000080,
};

#endif
