# SPDX-License-Identifier: GPL-2.0
#
# Makefile for nvmem drivers.
#

obj-$(CONFIG_NVMEM)		+= nvmem_core.o
nvmem_core-y			:= core.o

# Devices
obj-$(CONFIG_MTK_EFUSE)		+= nvmem_mtk-efuse.o
nvmem_mtk-efuse-y		:= mtk-efuse.o
