# UAPI Header export list
header-y += audio.h
header-y += ca.h
header-y += ca_tztv.h
header-y += dmx.h
header-y += dmx_tztv.h
header-y += frontend.h
header-y += frontend_tztv.h
header-y += net.h
header-y += osd.h
header-y += version.h
header-y += video.h
