#
#   Makefile for eXtended Sector Remapper (FSR) driver on kernel 2.6
#
#   Copyright(C) 2004-2006, Samsung Electronics, Co., Ltd.
#

# FSR base module
obj-$(CONFIG_TINY_FSR)			+= tfsr.o

# Should keep the build sequence. (fsr_base -> bml_block)
tfsr-objs	:= tfsr_base.o tfsr_block.o tfsr_blkdev.o

# This objects came from FSR, It will be never modified.
tfsr-objs	+= Core/BML/FSR_BML_ROInterface.o 
tfsr-objs	+= Core/BML/FSR_BML_BIFCommon.o 

tfsr-objs	+= Core/BML/FSR_BML_BBMCommon.o Core/BML/FSR_BML_BBMMount.o 

ifeq ($(CONFIG_ARCH_NVT72668),y)
tfsr-objs       += LLD/PND_NT668/FSR_LLD_PureNAND.o
tfsr-objs       += LLD/PND_NT668/FSR_LLD_NTK_NFC_Function.o
tfsr-objs       += PAM/NT668/FSR_PAM_NT668.o
tfsr-objs       += PAM/NT668/FSR_PAM_PND.o
endif

ifeq ($(CONFIG_ARCH_NVT72668),n)
tfsr-objs	+= LLD/FlexOND/FSR_LLD_FlexOND.o 
tfsr-objs       += LLD/OND/FSR_LLD_SWEcc.o LLD/OND/FSR_LLD_OneNAND.o
tfsr-objs       += LLD/OND/FSR_LLD_4K_OneNAND.o
endif

tfsr-objs	+= OAM/Linux/FSR_OAM_Linux.o

#tfsr-objs       += LLD/PND_NT668/FSR_LLD_NTK_NFC_Function.o

# Please add your platform here
ifeq ($(CONFIG_ARCH_NVT72668),n)
ifeq ($(CONFIG_MACH_OMAP_APOLLON),y)
tfsr-objs   += PAM/ApollonPLUS/FSR_PAM_ApollonPLUS.o
else
tfsr-objs   += PAM/Poseidon/FSR_PAM_Poseidon.o
endif #CONFIG_MACH_OMAP_APOLLON
endif

ifeq ($(CONFIG_ARM),y)
tfsr-objs   += PAM/Poseidon/FSR_PAM_asm.o
else
tfsr-objs   += PAM/Poseidon/FSR_PAM_Memcpy.o
endif #CONFIG_ARM

tfsr-objs	+= Misc/FSR_Version.o Misc/FSR_DBG_Zone.o 

