obj-$(CONFIG_ARCH_SDP1202)	+= sdp1202.o sdp1202_misc.o sdp1202_mpintr.o
obj-$(CONFIG_SDP_GPIO)		+= sdp1202_gpio.o
obj-$(CONFIG_CPU_FREQ)		+= sdp1202_cpufreq.o sdp1202_asv.o sdp1202_asv_mptrain.o
obj-$(CONFIG_SDP1202_THERMAL)	+= sdp1202_tmu.o
obj-$(CONFIG_SUSPEND)	+= sdp1202_suspend.o 
#sdp1202_micom_uart.o
